### ISSUE TITLE
If the model is valid and cannot be read please open an issue

### ISSUE THREAD

**Issue by jmol0917** [opencobra/cobrapy#1002]
Hi All,

I have been using cobrapy to model bugs from AGORA for the last year without any issues. Recently after installing a few packages (not related to GEMs) and updating python I started having an issue where all the 818 models are tagged as not valid. 

Basically when I run:
```
model = cobra.io.read_sbml_model(model_name)
```
I get the following error:
```
Traceback (most recent call last):
  File "C:\Users\jpmo_\Anaconda3\lib\site-packages\cobra\io\sbml.py", line 252, in read_sbml_model
    return _sbml_to_model(doc,
  File "C:\Users\jpmo_\Anaconda3\lib\site-packages\cobra\io\sbml.py", line 360, in _sbml_to_model
    cobra_model = Model(model_id)
  File "C:\Users\jpmo_\Anaconda3\lib\site-packages\cobra\core\model.py", line 117, in __init__
    self._solver = interface.Model()
AttributeError: 'NoneType' object has no attribute 'Model'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/Users/jpmo_/OneDrive/Documentos/GitHub/gsm_analysis/gsm_analysis/vitamin_production.py", line 208, in <module>
    model = cobra.io.read_sbml_model(path_in + file + '.xml')  # Models with the same name as 'file' are loaded
  File "C:\Users\jpmo_\Anaconda3\lib\site-packages\cobra\io\sbml.py", line 268, in read_sbml_model
    raise_from(cobra_error, original_error)
  File "<string>", line 3, in raise_from
cobra.io.sbml.CobraSBMLError: Something went wrong reading the SBML model. Most likely the SBML model is not valid. Please check that your model is valid using the `cobra.io.sbml.validate_sbml_model` function or via the online validator at http://sbml.org/validator .
	`(model, errors) = validate_sbml_model(filename)`
If the model is valid and cannot be read please open an issue at https://github.com/opencobra/cobrapy/issues .
```
I have confirmed that the paths are correct and I have tried running this using Jupyter notebooks and Pycharm and I have the same issue on both cases. 

This is what I get after running python -c "import cobra;cobra.show_versions()":

```
System Information
==================
OS         Windows
OS-release      10
Python       3.8.5

Package Versions
================
cobra                                    0.17.1
depinfo                                   1.5.3
future                                   0.18.2
numpy                                    1.19.1
optlang                                   1.4.4
pandas                                    1.1.1
pip                                      20.2.2
python-libsbml-experimental              5.18.0
ruamel.yaml                             0.16.10
setuptools                  49.6.0.post20200814
six                                      1.15.0
swiglpk                                  4.65.1
wheel                                    0.35.1
```
Thanks for your help.

**Comment by Midnighter** [comment]
Can you try with the latest cobrapy as well, please (version 0.19)?

**Comment by Midnighter** [comment]
Since you're using Anaconda, did you install cobra using pip or conda and the bioconda channel?

**Comment by jmol0917** [comment]
Thanks for the quick reply.
I will update my cobrapy version.
I am not 100% sure but I think I used pip. Should I try doing it with conda? 
Thanks!

**Comment by jmol0917** [comment]
I have updated cobra to its latest version and now I am having issues importing cobra:

```
Traceback (most recent call last):
  File "C:/Users/jpmo_/OneDrive/Documentos/GitHub/gsm_analysis/gsm_analysis/vitamin_production.py", line 14, in <module>
    import cobra
  File "C:\Users\jpmo_\Anaconda3\lib\site-packages\cobra\__init__.py", line 17, in <module>
    from cobra import io
  File "C:\Users\jpmo_\Anaconda3\lib\site-packages\cobra\io\__init__.py", line 8, in <module>
    from cobra.io.sbml import read_sbml_model, write_sbml_model, validate_sbml_model
  File "C:\Users\jpmo_\Anaconda3\lib\site-packages\cobra\io\sbml.py", line 41, in <module>
    import libsbml
  File "C:\Users\jpmo_\Anaconda3\lib\site-packages\libsbml\__init__.py", line 74141, in <module>
    class ArraysPkgNamespaces(SBMLNamespaces):
  File "C:\Users\jpmo_\Anaconda3\lib\site-packages\libsbml\__init__.py", line 74202, in ArraysPkgNamespaces
    __swig_destroy__ = _libsbml.delete_ArraysPkgNamespaces
AttributeError: module '_libsbml' has no attribute 'delete_ArraysPkgNamespaces'
```

**Comment by jmol0917** [comment]
I have updated cobra to its latest version but I'm still having the same issue. Even when I run

```
import cobra.test
model = cobra.test.create_test_model('textbook')
```
I get the same error:
```
AttributeError                            Traceback (most recent call last)
~\Anaconda3\lib\site-packages\cobra\io\sbml.py in read_sbml_model(filename, number, f_replace, **kwargs)
    250         doc = _get_doc_from_filename(filename)
--> 251         return _sbml_to_model(doc, number=number, f_replace=f_replace, **kwargs)
    252     except IOError as e:

~\Anaconda3\lib\site-packages\cobra\io\sbml.py in _sbml_to_model(doc, number, f_replace, set_missing_bounds, **kwargs)
    372         LOGGER.error("'%s' is not a valid SBML 'SId'." % model_id)
--> 373     cobra_model = Model(model_id)
    374     cobra_model.name = model.getName()

~\Anaconda3\lib\site-packages\cobra\core\model.py in __init__(self, id_or_model, name)
    120             interface = configuration.solver
--> 121             self._solver = interface.Model()
    122             self._solver.objective = interface.Objective(Zero)

AttributeError: 'NoneType' object has no attribute 'Model'

The above exception was the direct cause of the following exception:

CobraSBMLError                            Traceback (most recent call last)
<ipython-input-1-4e46d16fa750> in <module>
      1 import cobra.test
----> 2 model = cobra.test.create_test_model('textbook')

~\Anaconda3\lib\site-packages\cobra\test\__init__.py in create_test_model(model_name)
     35     elif model_name == "textbook":
     36         textbook_sbml = join(data_dir, "textbook.xml.gz")
---> 37         return read_sbml_model(textbook_sbml)
     38     elif model_name == "mini":
     39         mini_sbml = join(data_dir, "mini_fbc2.xml")

~\Anaconda3\lib\site-packages\cobra\io\sbml.py in read_sbml_model(filename, number, f_replace, **kwargs)
    263             "at https://github.com/opencobra/cobrapy/issues ."
    264         )
--> 265         raise_from(cobra_error, original_error)
    266 
    267 

~\Anaconda3\lib\site-packages\six.py in raise_from(value, from_value)

CobraSBMLError: Something went wrong reading the SBML model. Most likely the SBML model is not valid. Please check that your model is valid using the `cobra.io.sbml.validate_sbml_model` function or via the online validator at http://sbml.org/validator .
	`(model, errors) = validate_sbml_model(filename)`
If the model is valid and cannot be read please open an issue at https://github.com/opencobra/cobrapy/issues .
```

**Comment by Midnighter** [comment]
Something actually looks broken in optlang there. Can you please try in a fresh environment?

```
conda create -n test python=3.8
conda activate test
pip install cobra
```

**Comment by jmol0917** [comment]
Thanks for the help @Midnighter. When I run cobra in a fresh environment it does work just fine. I am unclear about which steps to take next though.

**Comment by Midnighter** [comment]
Seems to me that the path of least time/effort spent is to just go and set up your new environment and work with that.

**Comment by matthiaskoenig** [comment]
@jmol0917 Can we close this issue? This seems to be a problem with your local environment, but not with cobrapy.

**Comment by jmol0917** [comment]
Yes, please feel free to close it. It was a problem with my environment that was fixed by creating a new one.

Thanks
________________________________
