### ISSUE TITLE
cannot import name 'build_dist_index' from 'pipdeptree'

### ISSUE THREAD

**Issue by haraldschilly** [opencobra/cobrapy#1146]
#### Problem description

Upon `import cobra` I get

```
/usr/local/lib/python3.8/dist-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.      
  warnings.warn("Setuptools is replacing distutils.")                                                                       
Traceback (most recent call last):                                                                                          
  File "<string>", line 1, in <module>                                                                                      
  File "/usr/local/lib/python3.8/dist-packages/cobra/__init__.py", line 5, in <module>                                      
    from cobra.core import (                                                                                                
  File "/usr/local/lib/python3.8/dist-packages/cobra/core/__init__.py", line 1, in <module>                                 
    from cobra.core.configuration import Configuration                                                                      
  File "/usr/local/lib/python3.8/dist-packages/cobra/core/configuration.py", line 16, in <module>                           
    from cobra.util.solver import interface_to_str                                                                          
  File "/usr/local/lib/python3.8/dist-packages/cobra/util/__init__.py", line 4, in <module>                                 
    from cobra.util.util import *                                                                                           
  File "/usr/local/lib/python3.8/dist-packages/cobra/util/util.py", line 6, in <module>                                     
    from depinfo import print_dependencies                                                                                  
  File "/usr/local/lib/python3.8/dist-packages/depinfo/__init__.py", line 31, in <module>                                   
    from depinfo.info import *                                                                                              
  File "/usr/local/lib/python3.8/dist-packages/depinfo/info.py", line 27, in <module>                                       
    from pipdeptree import build_dist_index, construct_tree                                                                 
ImportError: cannot import name 'build_dist_index' from 'pipdeptree' (/usr/local/lib/python3.8/dist-packages/pipdeptree.py) 
```

### Context

python -c "import cobra;cobra.show_versions()"

well, that import doesn't work.

* cobra:  0.22.1
* pipdeptree: 2.2.1
* pip: 21.3.1
* Ubuntu 20.04.3 LTS

**Comment by Midnighter** [comment]
Can you run `pip install -U depinfo`, please? Or update/install into a new environment such that all dependencies are at the latest version, please?

**Comment by haraldschilly** [comment]
wow, that helped! I had `depinfo` at `1.5.3` → now `1.7.0` 

thank you!

**Comment by haraldschilly** [comment]
So, maybe this should be stated explicitly in [the dependencies here](https://github.com/opencobra/cobrapy/blob/devel/setup.cfg#L56) ?

**Comment by Midnighter** [comment]
Yeah, you're right. We should require a minimum version.
