### ISSUE TITLE
`cobra.flux_analysis.single_gene_deletion` blocks indefinitely in `waiter.acquire()`

### ISSUE THREAD

**Issue by irahorecka** [opencobra/cobrapy#1189]
#### Problem description

`cobra.flux_analysis.single_gene_deletion` blocks indefinitely in `waiter.acquire()` when performing all single deletions on this [model](https://github.com/SysBioChalmers/yeast-GEM/blob/main/model/yeast-GEM.xml). This behavior is seen in macOS and Linux environments.

#### Code Sample

Minimal reproducible code that monitors blocking in `single_gene_deletion` by incrementally processing 50 genes at a time.

```python
import time

import cobra
import lxml
from cobra.flux_analysis import single_gene_deletion


def load_model(sbml_path, solver="glpk"):
    """Loads model from SBML XML file."""
    model = cobra.io.read_sbml_model(sbml_path)
    model.solver = solver
    return model


def generate_deletion_flux(deletion_func, model, **kwargs):
    """Generates deletion flux pandas DataFrame by applying
    `deletion_func` to a model."""
    return deletion_func(model, **kwargs)


if __name__ == "__main__":
    model = load_model("yeast-GEM.xml")
    # Test multiprocessing gridlock in increments of 50 genes.
    for gene_num in range(10, 500, 50):
        t0 = time.time()
        try:
            single_deletion_flux = generate_deletion_flux(
                single_gene_deletion, model, gene_list=model.genes[:gene_num]
            )
        except KeyboardInterrupt as e:
            print(
                f"Process exited by user.\ntime elapsed processing {gene_num} genes: {round(time.time() - t0, 1)} sec"
            )
            raise KeyboardInterrupt from e
        print(f"time elapsed processing {gene_num} genes: {round(time.time() - t0, 1)} sec")
```

Full console log and traceback:
```
Scaling...
 A: min|aij| =  1.000e+00  max|aij| =  1.000e+00  ratio =  1.000e+00
Problem data seem to be well scaled
time elapsed processing 10 genes: 14.1 sec
time elapsed processing 60 genes: 13.6 sec
time elapsed processing 110 genes: 13.5 sec
^CProcess SpawnPoolWorker-24:
Process SpawnPoolWorker-23:
Process SpawnPoolWorker-28:
Process SpawnPoolWorker-25:
Process SpawnPoolWorker-27:
Process SpawnPoolWorker-22:
Process exited by user.
time elapsed processing 160 genes: 80.2 sec
Traceback (most recent call last):
  File "/Users/irahorecka/anaconda3/lib/python3.8/multiprocessing/pool.py", line 851, in next
    item = self._items.popleft()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "minimal_reproduction_gridlock_bug.py", line 27, in <module>
    single_deletion_flux = generate_deletion_flux(
  File "minimal_reproduction_gridlock_bug.py", line 18, in generate_deletion_flux
    return deletion_func(model, **kwargs)
  File "/Users/irahorecka/.virtualenvs/roest-lab/lib/python3.8/site-packages/cobra/flux_analysis/deletion.py", line 392, in single_gene_deletion
    return _multi_deletion(
  File "/Users/irahorecka/.virtualenvs/roest-lab/lib/python3.8/site-packages/cobra/flux_analysis/deletion.py", line 234, in _multi_deletion
    results = extract_knockout_results(
  File "/Users/irahorecka/.virtualenvs/roest-lab/lib/python3.8/site-packages/cobra/flux_analysis/deletion.py", line 213, in extract_knockout_results
    [
  File "/Users/irahorecka/.virtualenvs/roest-lab/lib/python3.8/site-packages/cobra/flux_analysis/deletion.py", line 213, in <listcomp>
    [
  File "/Users/irahorecka/anaconda3/lib/python3.8/multiprocessing/pool.py", line 448, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/Users/irahorecka/anaconda3/lib/python3.8/multiprocessing/pool.py", line 856, in next
    self._cond.wait(timeout)
  File "/Users/irahorecka/anaconda3/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
KeyboardInterrupt

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "minimal_reproduction_gridlock_bug.py", line 32, in <module>
    raise(KeyboardInterrupt) from e
KeyboardInterrupt
```

### Context

<details>

<b>macOS</b>
```
System Information
==================
OS         Darwin
OS-release 21.2.0
Python     3.8.12

Package Versions
================
appdirs                                      1.4.4
black                                      21.12b0
bumpversion ; extra == 'development' not installed
cobra                                       0.23.0
depinfo                                      1.7.0
diskcache                                    5.4.0
future                                      0.18.2
httpx                                       0.22.0
importlib-resources                          5.4.0
isort ; extra == 'development'       not installed
numpy                                       1.22.1
optlang                                      1.5.2
pandas                                       1.4.1
pip                                         22.0.4
pydantic                                     1.9.0
python-libsbml                              5.19.2
rich                                        12.0.0
ruamel.yaml                                0.17.21
scipy                                        1.7.3
setuptools                                  59.5.0
swiglpk                                      5.0.4
tox ; extra == 'development'         not installed
wheel                                       0.36.2
```

<b>Linux</b>
```
System Information
==================
OS                    Linux
OS-release 5.4.0-99-generic
Python                3.8.0

Package Versions
================
appdirs                                      1.4.4
black ; extra == 'development'       not installed
bumpversion ; extra == 'development' not installed
cobra                                       0.23.0
depinfo                                      1.7.0
diskcache                                    5.4.0
future                                      0.18.2
httpx                                       0.22.0
importlib-resources                          5.4.0
isort ; extra == 'development'       not installed
numpy                                       1.22.3
optlang                                      1.5.2
pandas                                       1.4.1
pip                                         22.0.4
pydantic                                     1.9.0
python-libsbml                              5.19.2
rich                                        12.0.0
ruamel.yaml                                0.17.21
scipy ; extra == 'array'             not installed
setuptools                                  60.9.3
swiglpk                                      5.0.4
tox ; extra == 'development'         not installed
wheel                                       0.37.1
```

</details>

**Comment by irahorecka** [comment]
I have experience working with multiprocessing and multithreading in my personal projects. I'd be happy to take a look into this on my end if that is of interest.

**Comment by Midnighter** [comment]
Thanks for the report! I haven't seen this yet on my end. Could you please upgrade cobrapy and if it still doesn't work, we definitely appreciate you investigating yourself.

**Comment by cdiener** [comment]
How do you know it really block in the acquire? Your output comes from interrupting the program manually and that will just give you the traceback of whatever random position it was interrupted at...

**Comment by irahorecka** [comment]
@Midnighter - The issue still persists in `cobra==0.24.0`.
@cdiener - That makes sense, but I tried this several times on both machines with the same traceback. I was tipped that a blockage occurred when a queue of 1000 genes ran for > 16 hours without completion. I wrote this minimal code snippet to investigate this issue further. Every time I exit the program when a process is taking unusually long to complete, I receive:

```
File "/Users/irahorecka/anaconda3/lib/python3.8/multiprocessing/pool.py", line 448, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/Users/irahorecka/anaconda3/lib/python3.8/multiprocessing/pool.py", line 856, in next
    self._cond.wait(timeout)
  File "/Users/irahorecka/anaconda3/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
```

The strange behavior is that the blockage isn't consistent in when it occurs. Though the pattern is the more genes there are queued, the more likely a blockage will happen.

**Comment by cdiener** [comment]
Hmm, yeah it could also just hang in the solver. The acquire is kind of the last thing that is called before it waits for the result. Maybe trying this with a different model with similar size (like E. coli) and seeing if it has the same problems might help. But definitely go ahead and investigate and let us know what you find :+1:

**Comment by cdiener** [comment]
I think this may be an issue with numerical stability and GLPK though. It works with cplex for me but will stall with GLPK even with a single process (that does not use multiprocessing). Lowering the tolerance with

```python
def load_model(sbml_path, solver="glpk"):
     """Loads model from SBML XML file."""
     model = cobra.io.read_sbml_model(sbml_path)
     model.solver = solver
     model.tolerance = 1e-6
     return model
```

works fine with multiprocessing for me (on Linux):

```
time elapsed processing 10 genes: 1.5 sec
time elapsed processing 60 genes: 2.1 sec
time elapsed processing 110 genes: 3.3 sec
time elapsed processing 160 genes: 4.2 sec
time elapsed processing 210 genes: 4.6 sec
time elapsed processing 260 genes: 5.3 sec
time elapsed processing 310 genes: 5.6 sec
time elapsed processing 360 genes: 5.1 sec
time elapsed processing 410 genes: 5.7 sec
time elapsed processing 460 genes: 6.1 sec
```

I do remember that there were some previous reports that specifically the Yeast GEM model is a hard cookie in terms of numerical accuracy. The condition number of the stoichiometric matrix is 3.6e17 which is definitely pretty horrible.

**Comment by irahorecka** [comment]
Fantastic - I was able to reproduce this on my end, as well. And good to know regarding the numerical accuracy issue of the yeast-GEM model. Thanks, @cdiener

**Comment by irahorecka** [comment]
Hey @cdiener, I've installed and am using cplex as my solver. You're right - the single deletion test works just fine without setting the model tolerance. However, when working with `double_gene_deletion` on the same model with one gene using one process, it appears the main thread is alive almost indefinitely, even to a point where `CTRL+C` will not kill the process.

I'm wondering if you have some insight on this? Below is a minimal reproducible code:

```python
import cobra
import lxml
from cobra.flux_analysis import double_gene_deletion


def load_model(sbml_path, solver="glpk"):
    """Loads model from SBML XML file."""
    model = cobra.io.read_sbml_model(sbml_path)
    model.solver = solver
    return model


def generate_deletion_flux(deletion_func, model, **kwargs):
    """Generates deletion flux pandas DataFrame by applying
    `deletion_func` to a model."""
    return deletion_func(model, **kwargs)


if __name__ == "__main__":
    model = load_model("yeast-GEM.xml", solver="cplex")
    generate_deletion_flux(double_gene_deletion, model, gene_list=model.genes[:1], processes=1)
```

**Comment by irahorecka** [comment]
Hey @cdiener, I've installed and am using cplex as my solver. You're right - the single deletion test works fine without adjusting the model tolerance. However, when working with `double_gene_deletion` on the same model with one gene using one process, it appears the main thread is alive almost indefinitely, even to a point where `CTRL+C` will not kill the process.

I'm wondering if you have some insight on this? Below is a minimal reproducible code:

```python
import cobra
import lxml
from cobra.flux_analysis import double_gene_deletion


def load_model(sbml_path, solver="glpk"):
    """Loads model from SBML XML file."""
    model = cobra.io.read_sbml_model(sbml_path)
    model.solver = solver
    return model


def generate_deletion_flux(deletion_func, model, **kwargs):
    """Generates deletion flux pandas DataFrame by applying
    `deletion_func` to a model."""
    return deletion_func(model, **kwargs)


if __name__ == "__main__":
    model = load_model("yeast-GEM.xml", solver="cplex")
    generate_deletion_flux(double_gene_deletion, model, gene_list=model.genes[:1], processes=1)
```

**Comment by cdiener** [comment]
Hard to say, might be the same issue again and you could try with lower tolerance or `model.solver.configuration.presolve = True`. But I would also check the RAM usage. Or maybe an edge case we don't handle? Does it also happen with two or three genes?

**Comment by Midnighter** [comment]
I also recommend setting optlang into verbose mode, then you can see solver output directly.

**Comment by irahorecka** [comment]
@cdiener - sounds good, I'll give two genes a try. I ran `double_gene_deletion` for one gene on 36 cores and it finished in ~2 hours. No multiprocessing block, however - which is great. I'll report back if something awry happens. But so far it looks good.
@Midnighter - thank you, this is good advice.

**Comment by cdiener** [comment]
Isn't the argument for double deletions called gene_list1 and gene_list2. It may also have ignored the arg and run all deletions which would take some time. What did your output look like?

**Comment by irahorecka** [comment]
Ah, I see - I assumed `double_gene_deletion` behaved similarly to `single_gene_deletion` in that it accepts a single argument for a list of genes ([doc](https://cobrapy.readthedocs.io/en/latest/deletions.html#Double-Deletions)). Using the `help` function made this clear. Seems like I was exhaustively making every double deletion possible, hence the long wait time. Thank you for the clarifications and help.

Using this call and setting cplex `optlang` to verbose mode:

```python
generate_deletion_flux(
        double_gene_deletion,
        model,
        gene_list1=(model.genes[1],),
        gene_list2=(model.genes[2],),
        processes=1,
    )
```

Output:
```
Version identifier: 20.1.0.0 | 2020-11-10 | 9bedb6d68
CPXPARAM_Preprocessing_Presolve                  0
CPXPARAM_Read_DataCheck                          1
CPXPARAM_LPMethod                                1
CPXPARAM_QPMethod                                1
CPXPARAM_Simplex_Tolerances_Optimality           9.9999999999999995e-08
CPXPARAM_Simplex_Tolerances_Feasibility          9.9999999999999995e-08
CPXPARAM_MIP_Tolerances_Integrality              9.9999999999999995e-08

Iteration log . . .
Iteration:     1    Scaled infeas =             0.054688
Iteration:    42    Scaled infeas =             0.054688
Iteration:   253    Scaled infeas =             0.054688
Iteration:   415    Scaled infeas =             0.054688
Perturbation started.
Switched to devex.
Iteration:   501    Scaled infeas =             0.054688
Iteration:   660    Scaled infeas =             0.054687
Iteration:   772    Scaled infeas =             0.054687
Iteration:   885    Scaled infeas =             0.054687
Iteration:  1001    Scaled infeas =             0.043750
Iteration:  1094    Scaled infeas =             0.043749
Iteration:  1191    Scaled infeas =             0.043749
Iteration:  1219    Objective     =             0.000000
Iteration:  1309    Objective     =             0.000001
Iteration:  1404    Objective     =             0.000003
Iteration:  1502    Objective     =             0.000005
Iteration:  1604    Objective     =             0.000006
Switched to steepest-edge.
Iteration:  1704    Objective     =             0.000008
Iteration:  1776    Objective     =             0.000015
Iteration:  1843    Objective     =             0.000030
Iteration:  1914    Objective     =             0.000047
Iteration:  1989    Objective     =             0.000089
Iteration:  2066    Objective     =             0.000202
Iteration:  2138    Objective     =             0.000590
Iteration:  2225    Objective     =             0.011474
Iteration:  2330    Objective     =             0.012196
Iteration:  2427    Objective     =             0.013879
Iteration:  2520    Objective     =             0.030255
Iteration:  2617    Objective     =             0.030259
Iteration:  2721    Objective     =             0.030259
Removing perturbation.
Iteration:  2743    Scaled infeas =             0.000000
Iteration:  2748    Objective     =             0.030249
```
