### ISSUE TITLE
error : from sympy.logic import boolalg as spl

### ISSUE THREAD

**Issue by Djamchid** [opencobra/cobrapy#1274]
#### please replace 

- <code>import sympy.logic.boolalg as spl</code>

> with 

- <code>from sympy.logic import boolalg as spl</code>

> in file cobra/core/gene.py

**Comment by Midnighter** [comment]
For what combination of versions of cobrapy and sympy?

**Comment by Djamchid** [comment]
I did "pip install cobrapy" this afternoon, then had a VERY hard time finding the reason behind the following execution error

```
.../Cobrapy$ python3 tuto.py 
Traceback (most recent call last):
  File "tuto.py", line 85, in <module>
    import cobra
  File "/home/djamchid/anaconda3/lib/python3.7/site-packages/cobra/__init__.py", line 5, in <module>
    from cobra.core import (
  File "/home/djamchid/anaconda3/lib/python3.7/site-packages/cobra/core/__init__.py", line 3, in <module>
    from cobra.core.gene import Gene, GPR
  File "/home/djamchid/anaconda3/lib/python3.7/site-packages/cobra/core/gene.py", line 24, in <module>
    import sympy.logic.boolalg as spl
ImportError: cannot import name 'boolalg' from 'sympy.core.logic' (/home/djamchid/anaconda3/lib/python3.7/site-packages/sympy/core/logic.py)
```

**Comment by Djamchid** [comment]
but I'm stuck with this error in masspy, any clues @Midnighter 

ImportError: cannot import name 'gene_to_dict' from 'cobra.io.dict'

Traceback (most recent call last):
  File "tuto.py", line 10, in <module>
    import mass
  File "/home/djamchid/anaconda3/lib/python3.7/site-packages/mass/__init__.py", line 7, in <module>
    from mass import enzyme_modules, io
  File "/home/djamchid/anaconda3/lib/python3.7/site-packages/mass/io/__init__.py", line 2, in <module>
    from mass.io.json import load_json_model, save_json_model
  File "/home/djamchid/anaconda3/lib/python3.7/site-packages/mass/io/json.py", line 30, in <module>
    from mass.io.dict import model_from_dict, model_to_dict
  File "/home/djamchid/anaconda3/lib/python3.7/site-packages/mass/io/dict.py", line 16, in <module>
    from cobra.io.dict import gene_from_dict, gene_to_dict
ImportError: cannot import name 'gene_to_dict' from 'cobra.io.dict' (/home/djamchid/anaconda3/lib/python3.7/site-packages/cobra/io/dict.py)

**Comment by Djamchid** [comment]
Maybe I found a workaround:

- <code>#from cobra.io.dict import gene_from_dict, gene_to_dict # modified by Djamchid 12.09.2022</code>
- <code>from cobra import io as cio # modified by Djamchid 12.09.2022</code>

**Comment by cdiener** [comment]
Not sure if it helps, but I have seen similar issues if you have sympy installed within a conda environment and via the normal non-conda pip as well. Uninstalling the non-conda one fixed it in that instance, but I could never found out why it would try to import packages from outside the conda env anyway...
