### ISSUE TITLE
[BUG] Numpy update broke load_matlab_model

### ISSUE THREAD

**Issue by cjrodriguez98** [opencobra/cobrapy#1406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I am trying to load a matlab model into cobrapy in a fresh enviroment and I am getting a numpy exception. 

cobra.io.load_matlab_model(Path('/scratch/cjrodriguezf/jobs/cancer/signaling_data', 'Human-GEM-1.14.0.mat'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch/cjrodriguezf/enviroments/cancer/lib/python3.9/site-packages/cobra/io/mat.py", line 341, in load_matlab_model
    return from_mat_struct(data[possible_name], model_id=possible_name, inf=inf)
  File "/scratch/cjrodriguezf/enviroments/cancer/lib/python3.9/site-packages/cobra/io/mat.py", line 872, in from_mat_struct
    if np.sctype2char(m["subSystems"][0, 0][0][0]) == "O" and isinstance(
  File "/scratch/cjrodriguezf/enviroments/cancer/lib/python3.9/site-packages/numpy/__init__.py", line 397, in __getattr__
    raise AttributeError(
AttributeError: `np.sctype2char` was removed in the NumPy 2.0 release. Use `np.dtype(obj).char` instead.

### Code sample

Code run:

```python
cobra.io.load_matlab_model(Path('/scratch/cjrodriguezf/jobs/cancer/signaling_data', 'Human-GEM-1.14.0.mat'))
```

Traceback:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch/cjrodriguezf/enviroments/cancer/lib/python3.9/site-packages/cobra/io/mat.py", line 341, in load_matlab_model
    return from_mat_struct(data[possible_name], model_id=possible_name, inf=inf)
  File "/scratch/cjrodriguezf/enviroments/cancer/lib/python3.9/site-packages/cobra/io/mat.py", line 872, in from_mat_struct
    if np.sctype2char(m["subSystems"][0, 0][0][0]) == "O" and isinstance(
  File "/scratch/cjrodriguezf/enviroments/cancer/lib/python3.9/site-packages/numpy/__init__.py", line 397, in __getattr__
    raise AttributeError(
AttributeError: `np.sctype2char` was removed in the NumPy 2.0 release. Use `np.dtype(obj).char` instead.

### Environment

<details>
Python 3.9.19
cobra 0.29.0
numpy 2.0.2
</details>

**Comment by cdiener** [comment]
Hi, this has already been [fixed in the code base](https://github.com/opencobra/cobrapy/pull/1397/commits/6ae5f09e30c7395a33e7dbe67329e290d93225ab) but we should make a release to deploy it. I will send one in.

**Comment by cjrodriguez98** [comment]
Thanks!
