### ISSUE TITLE
missing module pytest in devel branch

### ISSUE THREAD

**Issue by asuccurro** [opencobra/cobrapy#313]
Hello,

I pulled the devel branch and I get this error when testing, looks like a missing file:

```

>>> from cobra.test import solvers
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cobra/test/__init__.py", line 3, in <module>
    import pytest
ImportError: No module named pytest

```

**Comment by asuccurro** [comment]
my bad, I did not rerun the requirements after switching to devel !
