### ISSUE TITLE
Error message problems with optlang solution

### ISSUE THREAD

**Issue by pstjohn** [opencobra/cobrapy#371]
Happens when you try to access a reaction flux for a model that hasn't been solved:

```python
>>> import cobra.test
>>> model = cobra.test.create_test_model('textbook')
>>> model.reactions[0].x
Traceback (most recent call last):
  File "/Users/pstjohn/Packages/cobra_upstream/cobra/core/Reaction.py", line 351, in x
    return self._model.solution.x_dict[self.id]
  File "/Users/pstjohn/Packages/cobra_upstream/cobra/core/Solution.py", line 54, in x_dict
    return self.fluxes
  File "/Users/pstjohn/Packages/cobra_upstream/cobra/core/Solution.py", line 263, in fluxes
    self._check_freshness()
  File "/Users/pstjohn/Packages/cobra_upstream/cobra/core/Solution.py", line 241, in _check_freshness
    self.model._timestamp_last_optimization))
  File "/Users/pstjohn/Packages/cobra_upstream/cobra/core/Solution.py", line 233, in timestamp_formatter
    datetime.datetime.fromtimestamp(timestamp).strftime(
TypeError: an integer is required (got type NoneType)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pstjohn/Packages/cobra_upstream/cobra/core/Reaction.py", line 357, in x
    self._model.solution.status == "NA":
  File "/Users/pstjohn/Packages/cobra_upstream/cobra/core/Solution.py", line 246, in status
    self._check_freshness()
  File "/Users/pstjohn/Packages/cobra_upstream/cobra/core/Solution.py", line 241, in _check_freshness
    self.model._timestamp_last_optimization))
  File "/Users/pstjohn/Packages/cobra_upstream/cobra/core/Solution.py", line 233, in timestamp_formatter
    datetime.datetime.fromtimestamp(timestamp).strftime(
TypeError: an integer is required (got type NoneType)
```

**Comment by pstjohn** [comment]
sorry, thought this was a duplicate of #353

**Comment by Midnighter** [comment]
I've started to look into this and it's mostly solved. Asking for `x` of a reaction on an unsolved model now correctly returns `Exception: model has not been solved` in my branch. However, `.x` and `.flux` do not mirror each other. `.x` accesses the solution instance of the model whereas `.flux` accesses the `forward_` and `reverse_variable`'s primal directly (which is initialized to `0`) and returns `0.0` without error.

So even though `.x` uses the old solution interface the behavior seems more appropriate than `.flux`'s which I think uses the newer interface.

**Comment by pstjohn** [comment]
So I think we need to agree on the errors that should be coming out of something like .flux, .shadow_price, etc. when a model isn't solved... IMO `.flux` returning 0.0 with no error is a bug.

I believe @cdiener's suggestion (where did we talk about that?) was to return `None` when a solution wasn't valid, which I think is appropriate. 

What if `solution._is_current` returned True/False?

Then we could just say: 
`if not solution.is_current(): return None`
for Reaction.flux and company, (would that be a speed concern?)

and `if not solution.is_current(): raise UndefinedSolution` for the summary methods?

**Comment by Midnighter** [comment]
Check out the pull request #398.

I saw that the optlang interface code was returning None whereas the old code was raising an exception. I think in this case when you try to access solution attributes of a non-existent solution it's OK to be loud, i.e., raise an exception. I would agree that in the case of an optimization gone wrong that None or nan would be appropriate values.
