### ISSUE TITLE
Setting up environment for development fails with missing zmq

### ISSUE THREAD

**Issue by matthiaskoenig** [opencobra/cobrapy#447]
Hi all,
I wanted to contribute some fixes for the issues I have. But I cannot setup the development environment following
https://github.com/opencobra/cobrapy/blob/devel/CONTRIBUTING.rst

Installing the develop-requirements fails with

```
(cobrapy) mkoenig@core1:~/git/cobrapy$ pip install -r develop-requirements.txt Requirement already satisfied: six in /home/mkoenig/Envs/cobrapy/lib/python2.7/site-packages (from -r develop-requirements.txt (line 2))
Collecting Cython>=0.21 (from -r develop-requirements.txt (line 3))
  Downloading Cython-0.25.2-cp27-cp27mu-manylinux1_x86_64.whl (6.4MB)
    100% |████████████████████████████████| 6.4MB 217kB/s 
Collecting numpy>=1.6 (from -r develop-requirements.txt (line 4))
  Downloading numpy-1.12.0-cp27-cp27mu-manylinux1_x86_64.whl (16.5MB)
    100% |████████████████████████████████| 16.5MB 78kB/s 
Collecting scipy>=0.11.0 (from -r develop-requirements.txt (line 5))
  Downloading scipy-0.18.1-cp27-cp27mu-manylinux1_x86_64.whl (40.3MB)
    100% |████████████████████████████████| 40.3MB 29kB/s 
Collecting python-libsbml (from -r develop-requirements.txt (line 6))
  Downloading python_libsbml-5.13.0-cp27-cp27mu-manylinux1_x86_64.whl (24.0MB)
    100% |████████████████████████████████| 24.0MB 55kB/s 
Collecting lxml (from -r develop-requirements.txt (line 7))
  Downloading lxml-3.7.3-cp27-cp27mu-manylinux1_x86_64.whl (6.8MB)
    100% |████████████████████████████████| 6.8MB 208kB/s 
Collecting matplotlib (from -r develop-requirements.txt (line 8))
  Downloading matplotlib-2.0.0-1-cp27-cp27mu-manylinux1_x86_64.whl (14.6MB)
    100% |████████████████████████████████| 14.6MB 96kB/s 
Collecting palettable (from -r develop-requirements.txt (line 9))
  Downloading palettable-3.0.0-py2.py3-none-any.whl (72kB)
    100% |████████████████████████████████| 81kB 7.9MB/s 
Collecting zmq (from -r develop-requirements.txt (line 10))
  Downloading zmq-0.0.0.tar.gz
Collecting pymatbridge (from -r develop-requirements.txt (line 11))
  Downloading pymatbridge-0.5.2.tar.gz (978kB)
    100% |████████████████████████████████| 983kB 1.4MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-773X7e/pymatbridge/setup.py", line 16, in <module>
        from pymatbridge.messenger.make import get_messenger_dir
      File "pymatbridge/__init__.py", line 1, in <module>
        from .pymatbridge import *
      File "pymatbridge/pymatbridge.py", line 28, in <module>
        import zmq
    ImportError: No module named zmq
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-773X7e/pymatbridge/
(cobrapy) mkoenig@core1:~/git/cobrapy$ 

```

**Comment by matthiaskoenig** [comment]
Also shouldn't there be some checkout of the `develop` branch somewhere after 
1.cloning the repository
in https://github.com/opencobra/cobrapy/blob/devel/CONTRIBUTING.rst
Or should the pull request be against master? I am no expert with git, so sorry for these basic questions

**Comment by Midnighter** [comment]
Which Python, pip, and setuptools versions are you using? I created a new virtualenv with 2.7 and 3.5 just ran `pip install -r develop-requirements.txt` and it worked fine.

I still moved pymatbridge out of the file in #448 because I suspect hardly anyone needs it.

**Comment by matthiaskoenig** [comment]
Error occured with
```
pip 9.0.1 from /usr/local/lib/python2.7/dist-packages (python 2.7)
setuptools (34.1.0)
```
I upgraded to to 
```
setuptools (34.3.1)
```
but still see the problem.

**Comment by hredestig** [comment]
Sorry, we have really tried but can't reproduce this, if you can do some digging on your own and find the problem on the machine where you see the issue, it would be very helpful, otherwise I am afraid it's not much we can do at the moment.
