### ISSUE TITLE
ImportError: cannot import name _thread

### ISSUE THREAD

**Issue by celawson87** [opencobra/cobrapy#490]
Hello,

I am trying to install the latest version of cobrapy (0.6.05a) to take advantage of the tailored objectives capabilities and am running into trouble with importing the package:

```
from cobra.test import test_all
test_all()

No handlers could be found for logger "optlang"
/Users/christopherlawson/Library/Python/2.7/lib/python/site-packages/optlang/gurobi_interface.py:26: UserWarning: Be careful! The GUROBI interface is still under construction ...
  warn("Be careful! The GUROBI interface is still under construction ...")
/Users/christopherlawson/Library/Python/2.7/lib/python/site-packages/cobra/solvers/__init__.py:73: UserWarning: No LP solvers found
  warn("No LP solvers found")
Traceback (most recent call last):
  File "/Users/christopherlawson/PycharmProjects/modeling/cobrapy_test.py", line 1, in <module>
    from cobra.test import test_all
  File "/Users/christopherlawson/Library/Python/2.7/lib/python/site-packages/cobra/__init__.py", line 11, in <module>
    from cobra import design, flux_analysis, io
  File "/Users/christopherlawson/Library/Python/2.7/lib/python/site-packages/cobra/flux_analysis/__init__.py", line 9, in <module>
    from cobra.flux_analysis.loopless import (
  File "/Users/christopherlawson/Library/Python/2.7/lib/python/site-packages/cobra/flux_analysis/loopless.py", line 11, in <module>
    from cobra.core import Metabolite, Reaction, get_solution
  File "/Users/christopherlawson/Library/Python/2.7/lib/python/site-packages/cobra/core/__init__.py", line 6, in <module>
    from cobra.core.gene import Gene
  File "/Users/christopherlawson/Library/Python/2.7/lib/python/site-packages/cobra/core/gene.py", line 13, in <module>
    from cobra.util import resettable
  File "/Users/christopherlawson/Library/Python/2.7/lib/python/site-packages/cobra/util/__init__.py", line 8, in <module>
    from cobra.util.array import *
  File "/Users/christopherlawson/Library/Python/2.7/lib/python/site-packages/cobra/util/array.py", line 6, in <module>
    import pandas as pd
  File "/Users/christopherlawson/Library/Python/2.7/lib/python/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat.numpy import *
  File "/Users/christopherlawson/Library/Python/2.7/lib/python/site-packages/pandas/compat/__init__.py", line 357, in <module>
    from dateutil import parser as _date_parser
  File "/Library/Python/2.7/site-packages/dateutil/parser.py", line 43, in <module>
    from . import tz
  File "/Library/Python/2.7/site-packages/dateutil/tz/__init__.py", line 1, in <module>
    from .tz import *
  File "/Library/Python/2.7/site-packages/dateutil/tz/tz.py", line 23, in <module>
    from ._common import tzname_in_python2, _tzinfo, _total_seconds
  File "/Library/Python/2.7/site-packages/dateutil/tz/_common.py", line 2, in <module>
    from six.moves import _thread
ImportError: cannot import name _thread

Process finished with exit code 1
```

I am wondering if you could provided me with some guidance to get the package up and running.

Thanks!

**Comment by hredestig** [comment]
seems your datetuils installation is broken somehow (not related to cobrapy) perhaps you can 
```
pip uninstall python-dateutil
pip install python-dateutil --upgrade
```

**Comment by celawson87** [comment]
Hi Henning,

This seems to done the trick - thanks!

**Comment by hredestig** [comment]
Great to hear!

**Comment by mashnoon1234** [comment]
@hredestig the solution didn't work for me.

**Comment by Midnighter** [comment]
Hi @mashnoon1234, can you open a new issue with a detailed description of your problem, please? This issue is from two years ago and cobra is now at version 0.15.3.
