### ISSUE TITLE
Errors with reaction.remove_from_model and forward_variable

### ISSUE THREAD

**Issue by pstjohn** [opencobra/cobrapy#506]
This is failing on devel:

```python
import cobra
import cobra.test

model = cobra.test.create_test_model('textbook')

with model:
    model.reactions.PFK.remove_from_model()

model.reactions.PFK.forward_variable
```

Gives the error message:

```
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    model.reactions.PFK.remove_from_model()
  File "/Users/pstjohn/Packages/cobrapy/cobra/core/reaction.py", line 545, in remove_from_model
    self._model.remove_reactions([self], remove_orphans=remove_orphans)
  File "/Users/pstjohn/Packages/cobrapy/cobra/core/model.py", line 604, in remove_reactions
    forward = reaction.forward_variable
  File "/Users/pstjohn/Packages/cobrapy/cobra/core/reaction.py", line 143, in forward_variable
    assert self._forward_variable.problem is self.model.solver
AssertionError
```

Apparently the forward_variable.problem isn't being reset to the model's problem. I'll try to look into whats going on. Anyone have a good guess as to why that might be happening?

**Comment by pstjohn** [comment]
Looks like we need to reset the reaction variable cache. PR incoming

**Comment by pstjohn** [comment]
Apparently a larger issue, this is still failing on my PR:

```python
import cobra
import cobra.test

model = cobra.test.create_test_model('textbook')

with model:
    model.reactions.ATPM.remove_from_model()
    model.metabolites.atp_c.remove_from_model()


with model:
    model.reactions.ATPM.remove_from_model()
    model.metabolites.atp_c.remove_from_model()
```

**Comment by pstjohn** [comment]
Reopening just since we're still not out of the woods with that last problem. Looking into it now.

**Comment by hredestig** [comment]
Closing again with #508
