### ISSUE TITLE
Failure to install 0.9.0 via pip

### ISSUE THREAD

**Issue by WuyangFF95** [opencobra/cobrapy#604]
#### Problem description
I tried to update my cobrapy-0.8.2 to cobrapy-0.9.0, but failed. Therefore, I uninstalled my 0.8.2 version and tried again, and it failed once more.

Please explain:
* **what** you tried to achieve,
* **how** you went about it (referring to the code sample), and
* **why** the current behaviour is a problem and what output
  you expected instead.

#### Code Sample

Create a [minimal, complete, verifiable example
](https://stackoverflow.com/help/mcve).

```python
# Paste your code here.

pip install cobra[all]
```

#### Actual Output

Building wheels for collected packages: cobra
  Running setup.py bdist_wheel for cobra ... error
  Failed building wheel for cobra
  Running setup.py clean for cobra
Failed to build cobra
Installing collected packages: cobra
  Running setup.py install for cobra ... error
Exception:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\compat\__init__.py", line
 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 47: invalid
 continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\commands\install.py", lin
e 342, in run
    prefix=options.prefix_path,
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\req\req_set.py", line 784
, in install
    **kwargs
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\req\req_install.py", line
 878, in install
    spinner=spinner,
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\utils\__init__.py", line
676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\compat\__init__.py", line
 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 47: invalid
 continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\commands\install.py", lin
e 385, in run
    requirement_set.cleanup_files()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\req\req_set.py", line 729
, in cleanup_files
    req.remove_temporary_source()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\req\req_install.py", line
 977, in remove_temporary_source
    rmtree(self.source_dir)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\_vendor\retrying.py", lin
e 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\_vendor\retrying.py", lin
e 212, in call
    raise attempt.get()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\_vendor\retrying.py", lin
e 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "C:\ProgramData\Anaconda3\lib\site-packages\six.py", line 686, in reraise

    raise value
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\_vendor\retrying.py", lin
e 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\utils\__init__.py", line
102, in rmtree
    onerror=rmtree_errorhandler)
  File "C:\ProgramData\Anaconda3\lib\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\ProgramData\Anaconda3\lib\shutil.py", line 393, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\utils\__init__.py", line
114, in rmtree_errorhandler
    func(path)
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'C:\\Us
ers\\ADMINI~1.PC-\\AppData\\Local\\Temp\\pip-build-81afqld4\\cobra'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\basecommand.py", line 215
, in main
    status = self.run(options, args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\commands\install.py", lin
e 385, in run
    requirement_set.cleanup_files()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\utils\build.py", line 38,
 in __exit__
    self.cleanup()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\utils\build.py", line 42,
 in cleanup
    rmtree(self.name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\_vendor\retrying.py", lin
e 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\_vendor\retrying.py", lin
e 212, in call
    raise attempt.get()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\_vendor\retrying.py", lin
e 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "C:\ProgramData\Anaconda3\lib\site-packages\six.py", line 686, in reraise

    raise value
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\_vendor\retrying.py", lin
e 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\utils\__init__.py", line
102, in rmtree
    onerror=rmtree_errorhandler)
  File "C:\ProgramData\Anaconda3\lib\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\ProgramData\Anaconda3\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\ProgramData\Anaconda3\lib\shutil.py", line 393, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\utils\__init__.py", line
114, in rmtree_errorhandler
    func(path)
PermissionError: [WinError 32] Another program is using this file, the process cannot reach at this time. : 'C:\\Us
ers\\ADMINI~1.PC-\\AppData\\Local\\Temp\\pip-build-81afqld4\\cobra'
#### Output of `cobra.show_versions()`

<details>
# Paste the output of `import cobra;cobra.show_versions()` here.

</details>

**Comment by WuyangFF95** [comment]
I also downloaded the latest package from Github to try installing using:
pip install E:cobrapy-devel.zip
But again, it comes out with the same problem.

**Comment by Midnighter** [comment]
Well, it seems the Windows wheels for 0.9.0 are not on PyPi yet and trying to build the compiled extensions fails on your system. Let me take a look what happened to the wheels.

**Comment by Midnighter** [comment]
The AppVeyor logs for the tagged build show the following problem:
```
Collecting artifacts...
No artifacts found matching 'dist\*' path
if($env:appveyor_repo_tag -eq "True" -And $env:CONDA -ne "true") {
    Invoke-Expression "twine upload dist/* --username $env:PYPI_USERNAME --password $env:PYPI_PASSWORD"
}
```
@hredestig any idea what changed there?

**Comment by cdiener** [comment]
@Midnighter where do you see that error? I rather see:

```
twine : usage: twine upload [-h] [-r REPOSITORY] [--repository-url REPOSITORY_URL]
At line:1 char:1
+ twine upload dist/* --username  --password
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (usage: twine up...REPOSITORY_URL]:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
                    [-s] [--sign-with SIGN_WITH] [-i IDENTITY] [-u USERNAME]
                    [-p PASSWORD] [-c COMMENT] [--config-file CONFIG_FILE]
                    [--skip-existing] [--cert path] [--client-cert path]
                    dist [dist ...]
twine upload: error: argument -u/--username: expected one argument
Updating build cache...
```

which looks like the PyPi credentials were removed from appveyor...

**Comment by Midnighter** [comment]
I was looking at the conda builds which don't have the artifacts... My mistake. The PyPi credentials disappeared because we switched from Ali's AppVeyor account to mine (there are no organizations on AppVeyor :man_facepalming: ). I'll try to fix this as soon as possible but I'll need to contact @phantomas1234 for access to PyPi or his credentials.

**Comment by cdiener** [comment]
Yeah sounds good. Meanwhile uploading by hand should work for now.

**Comment by Midnighter** [comment]
Not without access :stuck_out_tongue_winking_eye:

**Comment by cdiener** [comment]
Ah sorry misread and though you switched from Alis *PyPi* account to yours :/

**Comment by WuyangFF95** [comment]
When will the Windows version of 0.9.0 wheel be available? @Midnighter @cdiener

**Comment by Midnighter** [comment]
We're juggling deployment accounts at the moment. Should be ready within the next few hours. I'll ping you.

**Comment by cdiener** [comment]
@WuyangFF95 the wheels are already there but not uploaded to PyPi yet. If you send me your Python version I can post the link to the wheel.

**Comment by cdiener** [comment]
Just saw you are using Anaconda so I'll assume you use Python 3.5 or 3.6, so here are the links for those two:

- 3.5: https://ci.appveyor.com/project/Midnighter/cobrapy/build/1.0.28/job/v19t4fft6guavtd5/artifacts 
- 3.6: https://ci.appveyor.com/project/Midnighter/cobrapy/build/1.0.28/job/cnx83np8h6h7sdts/artifacts

In both cases you need to download the `*.whl` file which you can install with pip

```bash
pip install cobra-0.9.0-more-text.whl
```

**Comment by cdiener** [comment]
Wheels are now on [PyPi](https://pypi.python.org/pypi/cobra/0.9.0). Feel free to reopen if that does not fix your issue :)
