### ISSUE TITLE
 cobra pie › install and use Gurobi solver

### ISSUE THREAD

**Issue by mjkijsc4** [opencobra/cobrapy#682]
Hi all 

I'm wanting to replicate flux predictions I made 3 years ago, in which I used Matlab, COBRA and the Gurobi solver. Interesting, as I'm now using Python and COBRApy and CPLEX solver but getting completely different flux distributions. Is this normal? So, I want to use the Gurobi solver with COBRApy to see if I replicate the results but I am having trouble with using the Gurobi solver.

So I installed the latest release of Gurobi Solver (gurobi7.5.2_mac64.pkg) and followed their installation wizard which installed the solver to the hard drive. I obtained the license and installed it here:

'/Users/stephenchapman/gurobi.lic'     (The solver is under '/Users/stephenchapman/Applications/'.

import cobra
import os
from os.path import join
data_dir = '/Users/stephenchapman/Documents/FBA_algae_digesate/COBRApy/models/iRC1080/'
model = cobra.io.read_sbml_model(join(data_dir, "IRC1080_SC_correctedPSII.xml"))
model
#<Model iRC1080 at 0x11ffc6048>  #the model reads fine!

model.solver ='gurobi'

output:
Traceback (most recent call last):
  File "/Users/stephenchapman/anaconda/lib/python3.6/site-packages/cobra/core/model.py", line 138, in solver
    interface = solvers[interface_to_str(value)]
KeyError: 'gurobi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/stephenchapman/anaconda/lib/python3.6/site-packages/cobra/util/context.py", line 69, in wrapper
    f(self, new_value)
  File "/Users/stephenchapman/anaconda/lib/python3.6/site-packages/cobra/core/model.py", line 140, in solver
    raise not_valid_interface
cobra.util.solver.SolverNotFound: gurobi is not a valid solver interface. Pick from ['glpk', 'scipy'], or specify an optlang interface (e.g. optlang.glpk_interface).

#### Output of `cobra.show_versions()`
<details>
>>> cobra.show_versions()
System Information
==================
OS              Darwin
OS-release      15.6.0
Python           3.6.1

Package Versions
================
pip              9.0.2
setuptools      27.2.0
cobra            0.8.2
future          0.16.0
swiglpk          1.4.4
optlang          1.2.3
ruamel.yaml    0.14.12
pandas          0.20.1
numpy           1.12.1
tabulate         0.8.1
python-libsbml  5.15.0
lxml             3.7.3
scipy           0.19.0
matplotlib       2.0.2

</details>

Any thoughts? I'm new to Python and I'm not a computer programmer, as you can tell. Is it something to do with the path of gurobi not being in the same path as COBRApy?

Cheers

**Comment by cdiener** [comment]
Unfortunately it looks like the Gurobi Python package was not installed. On what platform are you (Mac or Windows)? In case you use Anaconda you can install Gurobi with the following instructions:

http://www.gurobi.com/downloads/get-anaconda

**Comment by Midnighter** [comment]
Hey @mjkijsc4 in addition to what @cdiener said, to test your installation can you please try the following commands in your Python environment/interpreter:

```python
>>> import gurobipy
>>> gurobipy.Model()
```

and also

```python
>>> import optlang.gurobi_interface as grb
>>> grb.Model()
```

**Comment by Midnighter** [comment]
Closing due to inactivity.
