### ISSUE TITLE
cobra cannot install in python 3.7.0

### ISSUE THREAD

**Issue by tkosaka1976** [opencobra/cobrapy#734]
#### Problem description
Under Python 3.7.0, cobrapy cannot be installed.
Probably, dependent package ruamel.yaml<0.15 is the cause of problem.
I'm using macOS 10.13.6, Homebrew 1.6.14, python 3.7.0

#### Code Sample

```bash
pip3 install cobra

```

#### Actual Output
Collecting cobra
  Using cached https://files.pythonhosted.org/packages/05/5e/244535893f1fb3a61ee1da2c85f8f9c242f22e4ccc5c8881bfb20d51f1b7/cobra-0.13.0-py2.py3-none-any.whl
Requirement already satisfied: pandas>=0.17.0 in /usr/local/lib/python3.7/site-packages (from cobra) (0.23.1)
Requirement already satisfied: numpy>=1.13 in /usr/local/lib/python3.7/site-packages (from cobra) (1.14.5)
Requirement already satisfied: six in /usr/local/lib/python3.7/site-packages (from cobra) (1.11.0)
Collecting depinfo (from cobra)
  Using cached https://files.pythonhosted.org/packages/25/a4/75052b758112911810860bcef154596012232e339dad122d3ff443f179b8/depinfo-1.4.0-py2.py3-none-any.whl
Collecting optlang>=1.4.2 (from cobra)
  Using cached https://files.pythonhosted.org/packages/32/77/2bd1f39b0a555a3b44474911221c282092689c798dd7392c5138f8a2dd09/optlang-1.4.2-py2.py3-none-any.whl
Collecting ruamel.yaml<0.15 (from cobra)
  Using cached https://files.pythonhosted.org/packages/cf/86/7ef6c24317e20e6cef0eab407520d49f3d3836e454d5377bdcbcf03d385c/ruamel.yaml-0.14.12.tar.gz
    Complete output from command python setup.py egg_info:
    /var/folders/sy/h1y_hhn555z97z4n955vlqxc0000gn/T/tmp_ruamel_e4hnslb6/test_ruamel_yaml.c:6:8: warning: explicitly assigning value of variable of type 'yaml_parser_t' (aka 'struct yaml_parser_s') to itself [-Wself-assign]
    parser = parser;  /* prevent warning */
    ~~~~~~ ^ ~~~~~~
    /var/folders/sy/h1y_hhn555z97z4n955vlqxc0000gn/T/tmp_ruamel_e4hnslb6/test_ruamel_yaml.c:6:10: warning: variable 'parser' is uninitialized when used here [-Wuninitialized]
    parser = parser;  /* prevent warning */
             ^~~~~~
    /var/folders/sy/h1y_hhn555z97z4n955vlqxc0000gn/T/tmp_ruamel_e4hnslb6/test_ruamel_yaml.c:5:1: note: variable 'parser' is declared here
    yaml_parser_t parser;
    ^
    2 warnings generated.
    Warning: 'keywords' should be a list, got type 'NoneType'
    sys.argv ['-c', 'egg_info', '--egg-base', 'pip-egg-info']
    test compiling test_ruamel_yaml
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/sy/h1y_hhn555z97z4n955vlqxc0000gn/T/pip-install-cnq58krs/ruamel.yaml/setup.py", line 858, in <module>
        main()
      File "/private/var/folders/sy/h1y_hhn555z97z4n955vlqxc0000gn/T/pip-install-cnq58krs/ruamel.yaml/setup.py", line 847, in main
        setup(**kw)
      File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python3.7/site-packages/setuptools/dist.py", line 370, in __init__
        k: v for k, v in attrs.items()
      File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 267, in __init__
        getattr(self.metadata, "set_" + key)(val)
      File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 1203, in set_keywords
        self.keywords = _ensure_list(value, 'keywords')
      File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 40, in _ensure_list
        value = list(value)
    TypeError: 'NoneType' object is not iterable

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/sy/h1y_hhn555z97z4n955vlqxc0000gn/T/pip-install-cnq58krs/ruamel.yaml/

**Comment by Midnighter** [comment]
Okay, thank you for the report. It's high time to update the yaml dependency anyhow.

**Comment by Midnighter** [comment]
This is now fixed on devel and will be released soon.
