### ISSUE TITLE
feat: support pip 18.0

### ISSUE THREAD

**Issue by sulheim** [opencobra/cobrapy#780]
#### Problem description

Please explain:
* **what** you tried to achieve,
* **how** you went about it (referring to the code sample), and
* **why** the current behaviour is a problem and what output
  you expected instead.

#### Code Sample

Create a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve).

```console
>python -m pip install --upgrade pip
>python -c "import cobra"
```

#### Actual Output
Traceback (most recent call last):
  File "C:\Users\snorres\AppData\Local\Continuum\Anaconda3\lib\site-packages\pipdeptree.py", line 17, in <module>
    from pip._internal import get_installed_distributions
ImportError: cannot import name 'get_installed_distributions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\snorres\AppData\Local\Continuum\Anaconda3\lib\site-packages\cobra\__init__.py", line 11, in <module>
    from cobra import flux_analysis, io
  File "C:\Users\snorres\AppData\Local\Continuum\Anaconda3\lib\site-packages\cobra\flux_analysis\__init__.py", line 3, in <module>
    from cobra.flux_analysis.gapfilling import gapfill
  File "C:\Users\snorres\AppData\Local\Continuum\Anaconda3\lib\site-packages\cobra\flux_analysis\gapfilling.py", line 8, in <module>
    from cobra.core import Model
  File "C:\Users\snorres\AppData\Local\Continuum\Anaconda3\lib\site-packages\cobra\core\__init__.py", line 6, in <module>
    from cobra.core.gene import Gene
  File "C:\Users\snorres\AppData\Local\Continuum\Anaconda3\lib\site-packages\cobra\core\gene.py", line 13, in <module>
    from cobra.util import resettable
  File "C:\Users\snorres\AppData\Local\Continuum\Anaconda3\lib\site-packages\cobra\util\__init__.py", line 7, in <module>
    from cobra.util.util import *
  File "C:\Users\snorres\AppData\Local\Continuum\Anaconda3\lib\site-packages\cobra\util\util.py", line 5, in <module>
    from depinfo import print_dependencies
  File "C:\Users\snorres\AppData\Local\Continuum\Anaconda3\lib\site-packages\depinfo\__init__.py", line 27, in <module>
    from depinfo.info import *
  File "C:\Users\snorres\AppData\Local\Continuum\Anaconda3\lib\site-packages\depinfo\info.py", line 24, in <module>
    from pipdeptree import build_dist_index, construct_tree
  File "C:\Users\snorres\AppData\Local\Continuum\Anaconda3\lib\site-packages\pipdeptree.py", line 20, in <module>
    from pip import get_installed_distributions, FrozenRequirement
ImportError: cannot import name 'get_installed_distributions'

#### Dependency Information
Of obvious reasons i had to run python -m pip install pip==10 to run the 
`python -c "from cobra import show_versions;
show_versions()"`

So the pip-version is 18.1
<details>

System Information
==================
OS         Windows
OS-release      10
Python       3.5.2

Package Versions
================
cobra        0.13.4
depinfo       1.4.0
future       0.16.0
numpy        1.14.2
optlang       1.4.3
pandas       0.21.0
pip          10.0.0
ruamel.yaml 0.15.70
setuptools   39.2.0
six          1.11.0
swiglpk       1.4.4
tabulate      0.8.1
wheel        0.29.0
</details>

**Comment by sulheim** [comment]
https://github.com/pypa/pip/issues/5243#issuecomment-381513000

**Comment by Midnighter** [comment]
This is fixed if you also upgrade cobra's dependencies (`pipdeptree` being the culprit). You can upgrade them all with `pip install -U cobra`.

**Comment by sulheim** [comment]
Thanks!

**Comment by sulheim** [comment]
For anyone else encountering same issues:
`pip install -U cobra` didn't work for me, but `pip install --upgrade pipdeptree` does the job.
The version of pipdeptree should be 0.13.1

**Comment by Midnighter** [comment]
(I've edited the title to reflect that the problem is with 18.1.)
