### ISSUE TITLE
Unable to convert .mat to .sbml

### ISSUE THREAD

**Issue by pbordron** [opencobra/cobrapy#803]
#### Problem description

Please explain:
* **what** you tried to achieve,
I want to convert Recon3D .mat file from [https://www.vmh.life/#downloadview](https://www.vmh.life/#downloadview) in SBML format, but I get the following error with python 3 when importing the matlab model:

```
Traceback (most recent call last):
  File "mat2sbml.py", line 27, in <module>
    model = cobra.io.load_matlab_model(args.network_file)
  File "/home/filou/.local/miniconda3/envs/cobra-0.10.1/lib/python3.6/site-packages/cobra/io/mat.py", line 72, in load_matlab_model
    data = scipy_io.loadmat(infile_path)
  File "/home/filou/.local/miniconda3/envs/cobra-0.10.1/lib/python3.6/site-packages/scipy/io/matlab/mio.py", line 207, in loadmat
    MR, file_opened = mat_reader_factory(file_name, appendmat, **kwargs)
  File "/home/filou/.local/miniconda3/envs/cobra-0.10.1/lib/python3.6/site-packages/scipy/io/matlab/mio.py", line 63, in mat_reader_factory
    mjv, mnv = get_matfile_version(byte_stream)
  File "/home/filou/.local/miniconda3/envs/cobra-0.10.1/lib/python3.6/site-packages/scipy/io/matlab/miobase.py", line 222, in get_matfile_version
    mopt_bytes = fileobj.read(4)
  File "/home/filou/.local/miniconda3/envs/cobra-0.10.1/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 132: invalid start byte
```
If I switch to python 2.7, It pass through the utf-8 error, but the sbml export produces another error.

```
Traceback (most recent call last):
  File "mat2sbml.py", line 30, in <module>
    use_fbc_package=not args.legacy_sbml)
  File "/home/filou/.local/venv/cobra-0.14.2/lib/python2.7/site-packages/cobra/io/sbml3.py", line 718, in write_sbml_model
    write_sbml2(cobra_model, filename, use_fbc_package=False, **kwargs)
  File "/home/filou/.local/venv/cobra-0.14.2/lib/python2.7/site-packages/cobra/io/sbml.py", line 433, in write_cobra_model_to_sbml_file
    libsbml.writeSBML(sbml_doc, sbml_filename)
  File "/home/filou/.local/venv/cobra-0.14.2/lib/python2.7/site-packages/libsbml/__init__.py", line 2900, in writeSBML
    return _libsbml.writeSBML(d, filename)
TypeError: in method 'writeSBML', argument 2 of type 'char const *'
```

Thoses errors append either on my computer, with cobra 0.14.2, scipy 1.2.0 and libsbml 5.17.0 installation (see Dependency Information for details) and on a cluster infrastructure in a conda environment with cobra 0.10.1, scipy 1.2 and libsbml 5.12.0 (see also Dependency Information for details).

#### Code Sample

Here the python conversion script `mat2sbml.py`:

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import argparse
import cobra.io
import sys

parser = argparse.ArgumentParser(description='Convert a metabolic network matlab file into a sbml file.')
parser.add_argument('network_file', metavar="network.mat",
                    type=argparse.FileType('r'),
                    help='Metabolic network in Matlab format')
parser.add_argument('--variable-name', dest='variable_name', type=str,
                    help='Variable name')
parser.add_argument('-o', '--output', type=argparse.FileType('w'),
                    help='Output sbml file',
                    default=sys.stdout)
parser.add_argument('--legacy-sbml', dest='legacy_sbml', action='store_true',
                    default='False',
                    help='Use legacy sbml output format')

args = parser.parse_args()

if args.variable_name:
    model = cobra.io.load_matlab_model(args.network_file,
                                       variable_name=args.variable_name)
else:
    model = cobra.io.load_matlab_model(args.network_file)

cobra.io.write_sbml_model(model, args.output,
                          use_fbc_package=not args.legacy_sbml)

```

And a minimal example that reproduces the error

```bash
conda create -n cobra_py27 -c bioconda -c conda-forge cobra glpk scipy lxml python-libsbml python=2.7 wget
source activate cobra_py27
wget http://bigg.ucsd.edu/static/models/e_coli_core.mat
python mat2sbml.py e_coli_core.mat -o e_coli_core.xml
```

#### Dependency Information

Please paste the output of `python -c "from cobra import show_versions;
show_versions()"` in the details block below.

<details>

**Python 3 env**

System Information
==================
OS                    Linux
OS-release 4.20.3-1-MANJARO
Python                3.7.2

Package Versions
================
cobra        0.14.2
depinfo       1.4.0
future       0.17.1
numpy        1.16.1
optlang       1.4.4
pandas       0.24.1
pip          19.0.1
ruamel.yaml 0.15.87
setuptools   40.8.0
six          1.12.0
swiglpk      4.65.0
tabulate      0.8.3
wheel        0.32.3

**Python 2.7 env**

System Information
==================
OS                    Linux
OS-release 4.20.3-1-MANJARO
Python               2.7.15

Package Versions
================
cobra        0.14.2
depinfo       1.4.0
future       0.17.1
numpy        1.16.1
optlang       1.4.4
pandas       0.24.0
pip          19.0.1
ruamel.yaml 0.15.87
setuptools   40.7.2
six          1.12.0
swiglpk      4.65.0
tabulate      0.8.3
wheel        0.32.3

**conda env**

# packages in environment at /home/pbordron/miniconda3/envs/cobra-0.10.1_py27:
#
# Name                    Version                   Build  Channel
blas                      1.1                    openblas    conda-forge
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
certifi                   2018.11.29            py27_1000    conda-forge
cobra                     0.10.1                     py_1    bioconda
fastcache                 1.0.2           py27h14c3975_1001    conda-forge
future                    0.17.1                py27_1000    conda-forge
glpk                      4.57                          0    bioconda
gmp                       6.1.2             hf484d3e_1000    conda-forge
gmpy2                     2.0.8           py27hb20f59a_1002    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
libffi                    3.2.1             hf484d3e_1005    conda-forge
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-ng                 7.3.0                hdf63c60_0    conda-forge
libgfortran-ng            7.2.0                hdf63c60_3    conda-forge
libiconv                  1.15              h14c3975_1004    conda-forge
libstdcxx-ng              7.3.0                hdf63c60_0    conda-forge
libxml2                   2.9.8             h143f9aa_1005    conda-forge
libxslt                   1.1.32            h4785a14_1002    conda-forge
lxml                      4.3.0           py27h23eabaa_1000    conda-forge
mpc                       1.1.0             hb20f59a_1006    conda-forge
mpfr                      4.0.1             ha14ba45_1000    conda-forge
mpmath                    1.1.0                      py_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
numpy                     1.16.0          py27_blas_openblash1522bff_1000  [blas_openblas]  conda-forge
openblas                  0.3.3             h9ac9557_1001    conda-forge
openssl                   1.1.1a            h14c3975_1000    conda-forge
optlang                   1.4.4                      py_0    conda-forge
pandas                    0.24.0           py27hf484d3e_0    conda-forge
pcre                      8.41              hf484d3e_1003    conda-forge
pip                       19.0.1                   py27_0    conda-forge
python                    2.7.15               h9bab390_6  
python-dateutil           2.7.5                      py_0    conda-forge
python-libsbml            5.12.0           py27h05497bb_2    bioconda
pytz                      2018.9                     py_0    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
ruamel.ordereddict        0.4.13           py27h14c3975_0    conda-forge
ruamel.yaml               0.14.11                  py27_0    conda-forge
scipy                     1.2.0           py27_blas_openblash1522bff_1201  [blas_openblas]  conda-forge
setuptools                40.7.1                   py27_0    conda-forge
six                       1.12.0                py27_1000    conda-forge
sqlite                    3.26.0            h67949de_1000    conda-forge
swig                      3.0.12            hf484d3e_1003    conda-forge
swiglpk                   1.4.4                    py27_0    conda-forge
sympy                     1.3                   py27_1000    conda-forge
tabulate                  0.8.3                      py_0    conda-forge
tk                        8.6.9             h84994c4_1000    conda-forge
typing                    3.5.2.2                  py27_0    bioconda
wheel                     0.32.3                   py27_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge

</details>

**Comment by Midnighter** [comment]
I'm a bit surprised that no SBML is provided by the authors. Is that because they know it's not compatible?

**Comment by pbordron** [comment]
> I'm a bit surprised that no SBML is provided by the authors. Is that because they know it's not compatible?

Even if a Recon3D sbml existed[1] on the vmh website, this bug appends with the few .mat models I tried.

[1] It exists a Recon 3D sbml file that exists in BiGG but there is some differences with the original .mat file: [https://github.com/SBRG/bigg_models/issues/289](https://github.com/SBRG/bigg_models/issues/289)

**Comment by cdiener** [comment]
Hi I just tested and it worked fine for me. I could read the Matlab models (takes forever though) and write them to sbml without a hitch. 

If you don't write legacy SBML you currently don't need libSBML so I assume the error message for libSBML is seen only when writing to legacy format, correct? 

The first error could be due to the outdated cobrapy version. If do remember we did fix some issues with .mat import at some point. The second error has me stumped though. I will install libSBMl and report back if I see the same.

<details>

System Information
==================
OS                  Linux
OS-release 4.19.0-2-amd64
Python             3.7.2+

Package Versions
================
cobra        0.13.4
depinfo       1.4.0
future       0.17.1
numpy        1.16.1
optlang       1.4.3
pandas       0.24.1
pbr           5.1.1
pip          19.0.2
ruamel.yaml 0.15.80
setuptools   40.8.0
six          1.12.0
swiglpk      4.65.0
tabulate      0.8.2
wheel        0.32.3

</details>

**Comment by pbordron** [comment]
I get the error with and without the legacy sbml format.

I get the first error with python3, either with the last version of cobrapy (0.14.2) and the bioconda version (0.10.3) on different computers (my laptop and a cluster node)

I also get the second error with python2 the both computers. Either with and without conda
I have no error when loading the libsbml

```
python3
Python 3.7.2 (default, Jan 10 2019, 23:51:51) 
[GCC 8.2.1 20181127] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import libsbml
>>> 
```

```
$ python
Python 2.7.15 |Anaconda, Inc.| (default, Dec 14 2018, 19:04:19) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import libsbml
>>> 
```
related tests do not produce errors

```
$ python
Python 3.7.2 (default, Jan 10 2019, 23:51:51) 
[GCC 8.2.1 20181127] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from cobra.test import test_all
>>> test_all()
===================================================================== test session starts ======================================================================
platform linux -- Python 3.7.2, pytest-4.2.0, py-1.7.0, pluggy-0.8.1 -- /home/pbordron/venv/cobra-0.14.2-py3/bin/python
cachedir: .pytest_cache
benchmark: 3.2.2 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /home/pbordron, inifile:
plugins: benchmark-3.2.2
collected 79 items                                                                                                                                             

test/test_manipulation.py::TestManipulation::test_escape_ids PASSED                                                                                      [  1%]
test/test_manipulation.py::TestManipulation::test_rename_gene PASSED                                                                                     [  2%]
test/test_manipulation.py::TestManipulation::test_gene_knockout_computation PASSED                                                                       [  3%]
test/test_manipulation.py::TestManipulation::test_remove_genes PASSED                                                                                    [  5%]
test/test_manipulation.py::TestManipulation::test_sbo_annotation PASSED                                                                                  [  6%]
test/test_manipulation.py::TestManipulation::test_validate_formula_compartment PASSED                                                                    [  7%]
test/test_manipulation.py::TestManipulation::test_validate_mass_balance PASSED                                                                           [  8%]
test/test_manipulation.py::TestManipulation::test_prune_unused_mets_output_type PASSED                                                                   [ 10%]
test/test_manipulation.py::TestManipulation::test_prune_unused_mets_functionality PASSED                                                                 [ 11%]
test/test_manipulation.py::TestManipulation::test_prune_unused_rxns_output_type PASSED                                                                   [ 12%]
test/test_manipulation.py::TestManipulation::test_prune_unused_rxns_functionality PASSED                                                                 [ 13%]
test/test_medium.py::TestModelMedium::test_model_medium PASSED                                                                                           [ 15%]
test/test_medium.py::TestTypeDetection::test_external_compartment PASSED                                                                                 [ 16%]
test/test_medium.py::TestTypeDetection::test_multi_external PASSED                                                                                       [ 17%]
test/test_medium.py::TestTypeDetection::test_exchange PASSED                                                                                             [ 18%]
test/test_medium.py::TestTypeDetection::test_demand PASSED                                                                                               [ 20%]
test/test_medium.py::TestTypeDetection::test_sink PASSED                                                                                                 [ 21%]
test/test_medium.py::TestTypeDetection::test_sbo_terms PASSED                                                                                            [ 22%]
test/test_medium.py::TestMinimalMedia::test_medium_linear PASSED                                                                                         [ 24%]
test/test_medium.py::TestMinimalMedia::test_medium_mip PASSED                                                                                            [ 25%]
test/test_medium.py::TestMinimalMedia::test_medium_alternative_mip PASSED                                                                                [ 26%]
test/test_medium.py::TestMinimalMedia::test_benchmark_medium_linear SKIPPED                                                                              [ 27%]
test/test_medium.py::TestMinimalMedia::test_benchmark_medium_mip SKIPPED                                                                                 [ 29%]
test/test_medium.py::TestMinimalMedia::test_medium_exports PASSED                                                                                        [ 30%]
test/test_medium.py::TestMinimalMedia::test_open_exchanges PASSED                                                                                        [ 31%]
test/test_medium.py::TestErrorsAndExceptions::test_no_boundary_reactions PASSED                                                                          [ 32%]
test/test_medium.py::TestErrorsAndExceptions::test_no_names_or_boundary_reactions PASSED                                                                 [ 34%]
test/test_medium.py::TestErrorsAndExceptions::test_bad_exchange PASSED                                                                                   [ 35%]
test/test_io/test_io_order.py::test_io_order[metabolites-minimized_shuffle-read_sbml_model-write_sbml_model-.xml] PASSED                                 [ 36%]
test/test_io/test_io_order.py::test_io_order[metabolites-minimized_shuffle-load_json_model-save_json_model-.json] PASSED                                 [ 37%]
test/test_io/test_io_order.py::test_io_order[metabolites-minimized_shuffle-load_yaml_model-save_yaml_model-.yml] PASSED                                  [ 39%]
test/test_io/test_io_order.py::test_io_order[metabolites-minimized_reverse-read_sbml_model-write_sbml_model-.xml] PASSED                                 [ 40%]
test/test_io/test_io_order.py::test_io_order[metabolites-minimized_reverse-load_json_model-save_json_model-.json] PASSED                                 [ 41%]
test/test_io/test_io_order.py::test_io_order[metabolites-minimized_reverse-load_yaml_model-save_yaml_model-.yml] PASSED                                  [ 43%]
test/test_io/test_io_order.py::test_io_order[reactions-minimized_reverse-read_sbml_model-write_sbml_model-.xml] PASSED                                   [ 44%]
test/test_io/test_io_order.py::test_io_order[reactions-minimized_reverse-load_json_model-save_json_model-.json] PASSED                                   [ 45%]
test/test_io/test_io_order.py::test_io_order[reactions-minimized_reverse-load_yaml_model-save_yaml_model-.yml] PASSED                                    [ 46%]
test/test_io/test_io_order.py::test_io_order[reactions-minimized_shuffle-read_sbml_model-write_sbml_model-.xml] PASSED                                   [ 48%]
test/test_io/test_io_order.py::test_io_order[reactions-minimized_shuffle-load_json_model-save_json_model-.json] PASSED                                   [ 49%]
test/test_io/test_io_order.py::test_io_order[reactions-minimized_shuffle-load_yaml_model-save_yaml_model-.yml] PASSED                                    [ 50%]
test/test_io/test_io_order.py::test_io_order[reactions-minimized_sorted-read_sbml_model-write_sbml_model-.xml] PASSED                                    [ 51%]
test/test_io/test_io_order.py::test_io_order[reactions-minimized_sorted-load_json_model-save_json_model-.json] PASSED                                    [ 53%]
test/test_io/test_io_order.py::test_io_order[reactions-minimized_sorted-load_yaml_model-save_yaml_model-.yml] PASSED                                     [ 54%]
test/test_io/test_io_order.py::test_io_order[metabolites-minimized_sorted-read_sbml_model-write_sbml_model-.xml] PASSED                                  [ 55%]
test/test_io/test_io_order.py::test_io_order[metabolites-minimized_sorted-load_json_model-save_json_model-.json] PASSED                                  [ 56%]
test/test_io/test_io_order.py::test_io_order[metabolites-minimized_sorted-load_yaml_model-save_yaml_model-.yml] PASSED                                   [ 58%]
test/test_io/test_io_order.py::test_io_order[genes-minimized_sorted-read_sbml_model-write_sbml_model-.xml] PASSED                                        [ 59%]
test/test_io/test_io_order.py::test_io_order[genes-minimized_sorted-load_json_model-save_json_model-.json] PASSED                                        [ 60%]
test/test_io/test_io_order.py::test_io_order[genes-minimized_sorted-load_yaml_model-save_yaml_model-.yml] PASSED                                         [ 62%]
test/test_io/test_io_order.py::test_io_order[genes-minimized_reverse-read_sbml_model-write_sbml_model-.xml] PASSED                                       [ 63%]
test/test_io/test_io_order.py::test_io_order[genes-minimized_reverse-load_json_model-save_json_model-.json] PASSED                                       [ 64%]
test/test_io/test_io_order.py::test_io_order[genes-minimized_reverse-load_yaml_model-save_yaml_model-.yml] PASSED                                        [ 65%]
test/test_io/test_io_order.py::test_io_order[genes-minimized_shuffle-read_sbml_model-write_sbml_model-.xml] PASSED                                       [ 67%]
test/test_io/test_io_order.py::test_io_order[genes-minimized_shuffle-load_json_model-save_json_model-.json] PASSED                                       [ 68%]
test/test_io/test_io_order.py::test_io_order[genes-minimized_shuffle-load_yaml_model-save_yaml_model-.yml] PASSED                                        [ 69%]
test/test_io/test_json.py::test_validate_json XFAIL                                                                                                      [ 70%]
test/test_io/test_json.py::test_load_json_model PASSED                                                                                                   [ 72%]
test/test_io/test_json.py::test_save_json_model XFAIL                                                                                                    [ 73%]
test/test_io/test_mat.py::test_load_matlab_model PASSED                                                                                                  [ 74%]
test/test_io/test_mat.py::test_save_matlab_model PASSED                                                                                                  [ 75%]
test/test_io/test_pickle.py::test_read_pickle[load_function0] PASSED                                                                                     [ 77%]
test/test_io/test_pickle.py::test_read_pickle[None] SKIPPED                                                                                              [ 78%]
test/test_io/test_pickle.py::test_write_pickle[dump_function0] PASSED                                                                                    [ 79%]
test/test_io/test_pickle.py::test_write_pickle[None] SKIPPED                                                                                             [ 81%]
test/test_io/test_sbml.py::test_read_sbml_model PASSED                                                                                                   [ 82%]
test/test_io/test_sbml.py::test_read_file_handle PASSED                                                                                                  [ 83%]
test/test_io/test_sbml.py::test_write_sbml_model PASSED                                                                                                  [ 84%]
test/test_io/test_sbml3.py::test_benchmark_read SKIPPED                                                                                                  [ 86%]
test/test_io/test_sbml3.py::test_benchmark_write SKIPPED                                                                                                 [ 87%]
test/test_io/test_sbml3.py::test_sbml3_error PASSED                                                                                                      [ 88%]
test/test_io/test_sbml3.py::test_validate_sbml_model PASSED                                                                                              [ 89%]
test/test_io/test_sbml3.py::test_read_sbml_model[mini_fbc2.xml] PASSED                                                                                   [ 91%]
test/test_io/test_sbml3.py::test_read_sbml_model[mini_fbc2.xml.gz] PASSED                                                                                [ 92%]
test/test_io/test_sbml3.py::test_read_sbml_model[mini_fbc2.xml.bz2] PASSED                                                                               [ 93%]
test/test_io/test_sbml3.py::test_write_sbml_model[.xml] PASSED                                                                                           [ 94%]
test/test_io/test_sbml3.py::test_write_sbml_model[.xml.gz] PASSED                                                                                        [ 96%]
test/test_io/test_sbml3.py::test_write_sbml_model[.xml.bz2] PASSED                                                                                       [ 97%]
test/test_io/test_yaml.py::test_load_yaml_model PASSED                                                                                                   [ 98%]
test/test_io/test_yaml.py::test_save_yaml_model XFAIL                                                                                                    [100%]

======================================================================= warnings summary =======================================================================
/home/pbordron/venv/cobra-0.14.2-py3/lib/python3.7/site-packages/_pytest/config/__init__.py:730
  /home/pbordron/venv/cobra-0.14.2-py3/lib/python3.7/site-packages/_pytest/config/__init__.py:730 PytestWarning: Module already imported so cannot be rewritten: pytest_benchmark

test/test_manipulation.py::TestManipulation::test_escape_ids
  /home/pbordron/venv/cobra-0.14.2-py3/lib/python3.7/site-packages/optlang/interface.py:1358 DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working

test/test_manipulation.py::TestManipulation::test_gene_knockout_computation
test/test_manipulation.py::TestManipulation::test_sbo_annotation
test/test_manipulation.py::TestManipulation::test_prune_unused_rxns_output_type
test/test_manipulation.py::TestManipulation::test_prune_unused_rxns_functionality
test/test_manipulation.py::TestManipulation::test_prune_unused_rxns_functionality
test/test_manipulation.py::TestManipulation::test_prune_unused_rxns_functionality
test/test_medium.py::TestModelMedium::test_model_medium
test/test_medium.py::TestTypeDetection::test_demand
test/test_medium.py::TestTypeDetection::test_sink
  cobra/core/model.py:444 DeprecationWarning: add_reaction deprecated. Use add_reactions instead

test/test_medium.py::TestModelMedium::test_model_medium
test/test_medium.py::TestModelMedium::test_model_medium
  cobra/core/model.py:246 DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead

-- Docs: https://docs.pytest.org/en/latest/warnings.html
=================================================================== short test summary info ====================================================================
SKIPPED [4] /home/pbordron/venv/cobra-0.14.2-py3/lib/python3.7/site-packages/pytest_benchmark/plugin.py:396: Benchmarks are skipped (--benchmark-skip was used).
SKIPPED [1] /home/pbordron/venv/cobra-0.14.2-py3/lib/python3.7/site-packages/cobra/test/test_io/test_pickle.py:29: <Skipped instance>
SKIPPED [1] /home/pbordron/venv/cobra-0.14.2-py3/lib/python3.7/site-packages/cobra/test/test_io/test_pickle.py:41: <Skipped instance>
================================================ 70 passed, 6 skipped, 3 xfailed, 13 warnings in 32.08 seconds =================================================
0
```

**Comment by cdiener** [comment]
> I get the error with and without the legacy sbml format.

I don't understand. The error you pasted only applies to writing with `use_fbc_package=False`. Do you mean you get that error when running your script? This is because your `--legacy-sbml` arg has a wrong default type. The string `"False"` will always evaluate as true.

```Python3
In [1]: if "False": print("oh, okay...")
oh, okay...
```

If you use `default=False` that should change.

I think some of the errors you are seeing are due to the installation issues. Neither the `cobra` package, nor the `python-libsbml` packages from bioconda are officially supported. Both are outdated and currently unmaintained. For libsbml the official conda installation path is via their own channel as described [here](http://sbml.org/Software/libSBML/5.17.0/docs/python-api/libsbml-downloading.html) in Section 2. The `cobra` package on bioconda is not from us and we currently only support installation via pip. If you install python-libsbml via their channel (or with pip) and cobrapy with pip you should get a more predictable environment. I understand that our installation instructions are not really helpful if you are using conda and we should improve that.

I tried to reproduce your problem with Python 2 and could not do so. Here is what I did:

1. Download the Recon3D zip from the url you provided and unzipped the folder
2. cd'ed into the unzipped folder
3. created a Python 2 environment with `conda create -n cobra_py27 -c bioconda -c conda-forge glpk scipy lxml python=2.7`
4. activated the environment
5. Installed cobray and python-libsbml (closest version to yours) using pip: `pip install cobra "python-libsbml==5.12.1"`

The code I ran:

```Python
Python 2.7.15 | packaged by conda-forge | (default, Nov 28 2018, 14:39:28)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from cobra.io import load_matlab_model, write_sbml_model
>>> recon = load_matlab_model("Recon3D_301.mat")
>>> write_sbml_model(recon, "recon3d.xml")
>>> write_sbml_model(recon, "recon3d.xml", use_fbc_package=False)
>>> recon
<Model Recon3D at 0x1070b50d0>
```

which all runs without errors. So I am having a hard time getting the same errors as you. I can provide the converted SBML files if that helps you.

**Comment by pbordron** [comment]
> > I get the error with and without the legacy sbml format.
> 
> I don't understand. The error you pasted only applies to writing with `use_fbc_package=False`. Do you mean you get that error when running your script? This is because your `--legacy-sbml` arg has a wrong default type. The string `"False"` will always evaluate as true.
> 
> ```python
> In [1]: if "False": print("oh, okay...")
> oh, okay...
> ```
> 
> If you use `default=False` that should change.
> 

Shame on me. I didn't pay attention to it.
I have corrected it and now it's work ! 

Thx a lot

**Comment by cdiener** [comment]
No shame at all. Happens to all of us all the time! Glad it helped circumventing the issue at least : smile:
