### ISSUE TITLE
Problems checking for some stoichiometries in SBML reading

### ISSUE THREAD

**Issue by matthiaskoenig** [opencobra/cobrapy#843]
This is a bug in the attribute checking code.
```
Traceback (most recent call last):
  File "/home/mkoenig/git/cobrapy/cobra/io/sbml.py", line 212, in read_sbml_model
    **kwargs)
  File "/home/mkoenig/git/cobrapy/cobra/io/sbml.py", line 587, in _sbml_to_model
    "stoichiometry"))
  File "/home/mkoenig/git/cobrapy/cobra/io/sbml.py", line 1173, in _check_required
    raise CobraSBMLError(msg)
cobra.io.sbml.CobraSBMLError: required attribute 'stoichiometry' not found in '<SpeciesReference>'
None
```

**Comment by matthiaskoenig** [comment]
This is due to stochiometric coefficients of `0` and `0.0` in combination with an incorrect test.
E.g.
```
<speciesReference species="M_pg_monounsat_1g_m" stoichiometry="0" constant="true"/>
```
