### ISSUE TITLE
Error encountered trying to `set model history` when writing SBML

### ISSUE THREAD

**Issue by matthiaskoenig** [opencobra/cobrapy#850]
There is a known bug when writing the model history. This results in an error in the log 
```
Error encountered trying to `set model history` 
LibSBML error code -5: The object passed as an argument to the method is not of a type that is valid for the operation or kind of object involved. For example, handing an invalidly-constructed ASTNode to a method expecting an ASTNode will result in this error.
```
This does not affect the model in any way, but is only about writing provenance which is currently only experimental. This error can be savely ignored.

This depends on #810, i.e., how and what meta information to store on the model. As long as there is no decision on #810 it is not clear what the correct behavior is here, so just giving an error for now.

**Comment by prashantbajpai** [comment]
Hi Matthias,
It seems the model is being affected. While reading the model, I am getting the following error:
```
Traceback (most recent call last):
  File "/home/aarti/Desktop/prashant/myenv/lib/python3.5/site-packages/cobra/io/sbml.py", line 213, in read_sbml_model
    **kwargs)
  File "/home/aarti/Desktop/prashant/myenv/lib/python3.5/site-packages/cobra/io/sbml.py", line 454, in _sbml_to_model
    cobra_model.genes.append(cobra_gene)
  File "/home/aarti/Desktop/prashant/myenv/lib/python3.5/site-packages/cobra/core/dictlist.py", line 163, in append
    self._check(the_id)
  File "/home/aarti/Desktop/prashant/myenv/lib/python3.5/site-packages/cobra/core/dictlist.py", line 50, in _check
    raise ValueError("id %s is already present in list" % str(id))
ValueError: id  is already present in list
None
Traceback (most recent call last):
  File "/home/aarti/Desktop/prashant/myenv/lib/python3.5/site-packages/cobra/io/sbml.py", line 213, in read_sbml_model
    **kwargs)
  File "/home/aarti/Desktop/prashant/myenv/lib/python3.5/site-packages/cobra/io/sbml.py", line 454, in _sbml_to_model
    cobra_model.genes.append(cobra_gene)
  File "/home/aarti/Desktop/prashant/myenv/lib/python3.5/site-packages/cobra/core/dictlist.py", line 163, in append
    self._check(the_id)
  File "/home/aarti/Desktop/prashant/myenv/lib/python3.5/site-packages/cobra/core/dictlist.py", line 50, in _check
    raise ValueError("id %s is already present in list" % str(id))
ValueError: id  is already present in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aarti/Desktop/prashant/myenv/lib/python3.5/site-packages/cobra/io/sbml.py", line 220, in read_sbml_model
    "Something went wrong reading the SBML model. Most likely the SBML"
cobra.io.sbml.CobraSBMLError: Something went wrong reading the SBML model. Most likely the SBML model is not valid. Please check that your model is valid using the `cobra.io.sbml.validate_sbml_model` function or via the online validator at http://sbml.org/validator .
	`(model, errors) = validate_sbml_model(filename)`
If the model is valid and cannot be read please open an issue at https://github.com/opencobra/cobrapy/issues 
```
Here is my model and this is what I did:
[mitocore_updated_15_04.xml.tar.gz](https://github.com/opencobra/cobrapy/files/3246714/mitocore_updated_15_04.xml.tar.gz)

```
import cobra
mymodel = cobra.io.read_sbml_model("mitocore_updated_15_04.xml")
mymodel.optimize()
cobra.io.write_sbml_model("test.xml")
mymodel2 = cobra.io.read_sbml_model("test.xml")
```
Please let me know what I am doing wrong. I did try validating it with ```validate_sbml_model``` but it seems to be giving error for all the models (even Recon3D I downloaded from BIGG).

**Comment by matthiaskoenig** [comment]
Hi @prashantbajpai,
thanks for reporting this. I am very sure this is an unrelated bug. 

My first intuition is that the problem is that your model is invalid, more specifically has invalid ids.
If you run the model through the SBML validator you see that you have invalid ids in your model (as stated in the error message `Most likely the SBML model is not valid. Please check that your model is valid using the `cobra.io.sbml.validate_sbml_model` function or via the online validator at http://sbml.org/validator.`)
The incorrect ids will most likely result in the issues because some ids cannot be parsed and then are lost on export (they never exist).
E.g.,
```
The syntax of 'id' attribute values must conform to the syntax of the SBML type 'SId'. Reference: L3V1 Section 3.1.7 The syntax of the attribute id='G_Non-enzymatic' does not conform.
```
We provide full support for valid SBML models, unfortunately there is no way we can support invalid SBML. Please fix the model, if the issue remains I will fix the issue in cobrapy (but like mentioned above, I am very sure the issue are the invalid model ids).

The full stack of errors in your model are:
```
Error Line 153 Column 115: (SBML Validation Rule #fbc-20303) The value of attribute 'fbc:chemicalFormula' on the SBML <species> object must be set to a string consisting only of atomic names or user defined compounds and their occurrence. Reference: L3V1 Fbc V2 Section 3.4 Encountered '/' when expecting a capital letter.The chemicalFormula 'N/A' has incorrect syntax.

<species boundaryCondition="false" constant="false" hasOnlySubstanceUnits="false" id="M_biomass_c" name="Biomass" compartment="Cytosol" fbc:charge="0" fbc:chemicalFormula="N/A"/>

Error Line 154 Column 115: (SBML Validation Rule #fbc-20303) The value of attribute 'fbc:chemicalFormula' on the SBML <species> object must be set to a string consisting only of atomic names or user defined compounds and their occurrence. Reference: L3V1 Fbc V2 Section 3.4 Encountered '/' when expecting a capital letter.The chemicalFormula 'N/A' has incorrect syntax.

<species boundaryCondition="false" constant="false" hasOnlySubstanceUnits="false" id="M_biomass_m" name="Biomass" compartment="Mitochondrion" fbc:charge="0" fbc:chemicalFormula="N/A"/>

Error Line 1854 Column 49: (SBML Validation Rule #10310Error Line 153 Column 115: (SBML Validation Rule #fbc-20303) The value of attribute 'fbc:chemicalFormula' on the SBML <species> object must be set to a string consisting only of atomic names or user defined compounds and their occurrence. Reference: L3V1 Fbc V2 Section 3.4 Encountered '/' when expecting a capital letter.The chemicalFormula 'N/A' has incorrect syntax.

<species boundaryCondition="false" constant="false" hasOnlySubstanceUnits="false" id="M_biomass_c" name="Biomass" compartment="Cytosol" fbc:charge="0" fbc:chemicalFormula="N/A"/>

Error Line 154 Column 115: (SBML Validation Rule #fbc-20303) The value of attribute 'fbc:chemicalFormula' on the SBML <species> object must be set to a string consisting only of atomic names or user defined compounds and their occurrence. Reference: L3V1 Fbc V2 Section 3.4 Encountered '/' when expecting a capital letter.The chemicalFormula 'N/A' has incorrect syntax.

<species boundaryCondition="false" constant="false" hasOnlySubstanceUnits="false" id="M_biomass_m" name="Biomass" compartment="Mitochondrion" fbc:charge="0" fbc:chemicalFormula="N/A"/>

Error Line 1854 Column 49: (SBML Validation Rule #10310) The syntax of 'id' attribute values must conform to the syntax of the SBML type 'SId'. Reference: L3V1 Section 3.1.7 The syntax of the attribute id='G_N/A' does not conform.

<fbc:geneProduct fbc:id="G_N/A" fbc:label="N/A" fbc:name="N/A"/>

Error Line 1862 Column 49: (SBML Validation Rule #10310) The syntax of 'id' attribute values must conform to the syntax of the SBML type 'SId'. Reference: L3V1 Section 3.1.7 The syntax of the attribute id='G_Non-Enzymatic' does not conform.

<fbc:geneProduct fbc:id="G_Non-Enzymatic" fbc:label="Non-Enzymatic" fbc:name="Non-Enzymatic"/>

Error Line 1918 Column 49: (SBML Validation Rule #10310) The syntax of 'id' attribute values must conform to the syntax of the SBML type 'SId'. Reference: L3V1 Section 3.1.7 The syntax of the attribute id='G_Non-enzymatic' does not conform.

<fbc:geneProduct fbc:id="G_Non-enzymatic" fbc:label="Non-enzymatic" fbc:name="Non-enzymatic"/>

Error Line 4648 Column 11: (SBML Validator Check #2020904) The syntax of the attribute geneProduct='G_N/A' does not conform.

<fbc:geneProductRef fbc:geneProduct="G_ENSG00000120053"/>

Error Line 4776 Column 7: (SBML Validator Check #2020904) The syntax of the attribute geneProduct='G_Non-Enzymatic' does not conform.

<reaction fast="false" id="R_TRPO2" reversible="false" name="R_TRPO2 L-Tryptophan + Oxygen --&gt; L-Formylkynurenine" fbc:upperFluxBound="cobra_default_ub" fbc:lowerFluxBound="cobra_0_bound">

Error Line 5150 Column 11: (SBML Validator Check #2020904) The syntax of the attribute geneProduct='G_Non-Enzymatic' does not conform.

<speciesReference constant="true" species="M_PMF_c" stoichiometry="0.82"/>

Error Line 5277 Column 7: (SBML Validator Check #2020904) The syntax of the attribute geneProduct='G_Non-Enzymatic' does not conform.

<reaction fast="false" id="R_ORNTArm" reversible="true" name="R_ORNTArm L-Ornithine + 2-Oxoglutarate --&gt; L-Glutamate 5-semialdehyde + L-Glutamate" fbc:upperFluxBound="cobra_default_ub" fbc:lowerFluxBound="cobra_default_lb">

Error Line 6054 Column 11: (SBML Validator Check #2020904) The syntax of the attribute geneProduct='G_Non-enzymatic' does not conform.

<speciesReference constant="true" species="M_arg_L_c" stoichiometry="1"/>

Error Line 6576 Column 7: (SBML Validator Check #2020904) The syntax of the attribute geneProduct='G_N/A' does not conform.

<reaction fast="false" id="R_AMPD1" reversible="false" name="R_AMPD1 AMP + H2O --&gt; IMP + Ammonia" fbc:upperFluxBound="cobra_default_ub" fbc:lowerFluxBound="cobra_0_bound"> Reference: L3V1 Section 3.1.7 The syntax of the attribute id='G_N/A' does not conform.

<fbc:geneProduct fbc:id="G_N/A" fbc:label="N/A" fbc:name="N/A"/>

Error Line 1862 Column 49: (SBML Validation Rule #10310) The syntax of 'id' attribute values must conform to the syntax of the SBML type 'SId'. Reference: L3V1 Section 3.1.7 The syntax of the attribute id='G_Non-Enzymatic' does not conform.

<fbc:geneProduct fbc:id="G_Non-Enzymatic" fbc:label="Non-Enzymatic" fbc:name="Non-Enzymatic"/>

Error Line 1918 Column 49: (SBML Validation Rule #10310) The syntax of 'id' attribute values must conform to the syntax of the SBML type 'SId'. Reference: L3V1 Section 3.1.7 The syntax of the attribute id='G_Non-enzymatic' does not conform.

<fbc:geneProduct fbc:id="G_Non-enzymatic" fbc:label="Non-enzymatic" fbc:name="Non-enzymatic"/>

Error Line 4648 Column 11: (SBML Validator Check #2020904) The syntax of the attribute geneProduct='G_N/A' does not conform.

<fbc:geneProductRef fbc:geneProduct="G_ENSG00000120053"/>

Error Line 4776 Column 7: (SBML Validator Check #2020904) The syntax of the attribute geneProduct='G_Non-Enzymatic' does not conform.

<reaction fast="false" id="R_TRPO2" reversible="false" name="R_TRPO2 L-Tryptophan + Oxygen --&gt; L-Formylkynurenine" fbc:upperFluxBound="cobra_default_ub" fbc:lowerFluxBound="cobra_0_bound">

Error Line 5150 Column 11: (SBML Validator Check #2020904) The syntax of the attribute geneProduct='G_Non-Enzymatic' does not conform.

<speciesReference constant="true" species="M_PMF_c" stoichiometry="0.82"/>

Error Line 5277 Column 7: (SBML Validator Check #2020904) The syntax of the attribute geneProduct='G_Non-Enzymatic' does not conform.

<reaction fast="false" id="R_ORNTArm" reversible="true" name="R_ORNTArm L-Ornithine + 2-Oxoglutarate --&gt; L-Glutamate 5-semialdehyde + L-Glutamate" fbc:upperFluxBound="cobra_default_ub" fbc:lowerFluxBound="cobra_default_lb">

Error Line 6054 Column 11: (SBML Validator Check #2020904) The syntax of the attribute geneProduct='G_Non-enzymatic' does not conform.

<speciesReference constant="true" species="M_arg_L_c" stoichiometry="1"/>

Error Line 6576 Column 7: (SBML Validator Check #2020904) The syntax of the attribute geneProduct='G_N/A' does not conform.

<reaction fast="false" id="R_AMPD1" reversible="false" name="R_AMPD1 AMP + H2O --&gt; IMP + Ammonia" fbc:upperFluxBound="cobra_default_ub" fbc:lowerFluxBound="cobra_0_bound">
```

**Comment by prashantbajpai** [comment]
Thanks Matthias. I will correct the model IDs. However, If model IDs is the issue, why does running ``` mymodel = cobra.io.read_sbml_model("mitocore_updated_15_04.xml")``` doesn't throw an error? I get the error only after writing it and reading again.

**Comment by matthiaskoenig** [comment]
@prashantbajpai Yes, this is indeed a bug. You should get this information as error on model reading. I opened an issue for that in #851.
