### ISSUE TITLE
Fix broken docs

### ISSUE THREAD

**Issue by synchon** [opencobra/cobrapy#868]
The current state of docs is broken. It would be great to fix it ASAP.

**Comment by Midnighter** [comment]
Actually, there still is a problem.

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/cobrapy/envs/0.15.4/lib/python3.7/site-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cobrapy/envs/0.15.4/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cobrapy/checkouts/0.15.4/documentation_builder/conf.py", line 90, in <module>
    from cobra import __version__ as release
  File "/home/docs/checkouts/readthedocs.org/user_builds/cobrapy/checkouts/0.15.4/cobra/__init__.py", line 14, in <module>
    from cobra import flux_analysis
  File "/home/docs/checkouts/readthedocs.org/user_builds/cobrapy/checkouts/0.15.4/cobra/flux_analysis/__init__.py", line 3, in <module>
    from cobra.flux_analysis.deletion import (
  File "/home/docs/checkouts/readthedocs.org/user_builds/cobrapy/checkouts/0.15.4/cobra/flux_analysis/deletion.py", line 10, in <module>
    from optlang.exceptions import SolverError
ModuleNotFoundError: No module named 'optlang.exceptions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/cobrapy/envs/0.15.4/lib/python3.7/site-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cobrapy/envs/0.15.4/lib/python3.7/site-packages/sphinx/application.py", line 201, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cobrapy/envs/0.15.4/lib/python3.7/site-packages/sphinx/config.py", line 203, in read
    namespace = eval_config_file(filename, tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cobrapy/envs/0.15.4/lib/python3.7/site-packages/sphinx/config.py", line 380, in eval_config_file
    raise ConfigError(msg % traceback.format_exc())
sphinx.errors.ConfigError: There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/cobrapy/envs/0.15.4/lib/python3.7/site-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cobrapy/envs/0.15.4/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cobrapy/checkouts/0.15.4/documentation_builder/conf.py", line 90, in <module>
    from cobra import __version__ as release
  File "/home/docs/checkouts/readthedocs.org/user_builds/cobrapy/checkouts/0.15.4/cobra/__init__.py", line 14, in <module>
    from cobra import flux_analysis
  File "/home/docs/checkouts/readthedocs.org/user_builds/cobrapy/checkouts/0.15.4/cobra/flux_analysis/__init__.py", line 3, in <module>
    from cobra.flux_analysis.deletion import (
  File "/home/docs/checkouts/readthedocs.org/user_builds/cobrapy/checkouts/0.15.4/cobra/flux_analysis/deletion.py", line 10, in <module>
    from optlang.exceptions import SolverError
ModuleNotFoundError: No module named 'optlang.exceptions'


Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/cobrapy/envs/0.15.4/lib/python3.7/site-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cobrapy/envs/0.15.4/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cobrapy/checkouts/0.15.4/documentation_builder/conf.py", line 90, in <module>
    from cobra import __version__ as release
  File "/home/docs/checkouts/readthedocs.org/user_builds/cobrapy/checkouts/0.15.4/cobra/__init__.py", line 14, in <module>
    from cobra import flux_analysis
  File "/home/docs/checkouts/readthedocs.org/user_builds/cobrapy/checkouts/0.15.4/cobra/flux_analysis/__init__.py", line 3, in <module>
    from cobra.flux_analysis.deletion import (
  File "/home/docs/checkouts/readthedocs.org/user_builds/cobrapy/checkouts/0.15.4/cobra/flux_analysis/deletion.py", line 10, in <module>
    from optlang.exceptions import SolverError
ModuleNotFoundError: No module named 'optlang.exceptions'
```

**Comment by cdiener** [comment]
Is this from a recent build? The PR added optlang.exceptions to the mock import...
