### ISSUE TITLE
AttributeError: module '__main__' has no attribute '__spec__'

### ISSUE THREAD

**Issue by tanialbb** [opencobra/cobrapy#898]
#### Problem description
I'm trying to run FVA:
```
from cobra.flux_analysis import flux_variability_analysis
flux_variability_analysis(HMR2model, HMR2model.reactions[:10])
```
But I get the error:
`Traceback (most recent call last):
  File "C:\Users\Tania\.conda\envs\models\lib\site-packages\IPython\core\interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-381-0f6c0f521409>", line 1, in <module>
    flux_variability_analysis(HMR2model, HMR2model.reactions[:10]) # at 90% of massimum capacity of biomass flux
  File "C:\Users\Tania\.conda\envs\models\lib\site-packages\cobra\flux_analysis\variability.py", line 187, in flux_variability_analysis
    initargs=(model, loopless, what[:3])
  File "C:\Users\Tania\.conda\envs\models\lib\multiprocessing\context.py", line 118, in Pool
    context=self.get_context())
  File "C:\Users\Tania\.conda\envs\models\lib\multiprocessing\pool.py", line 174, in __init__
    self._repopulate_pool()
  File "C:\Users\Tania\.conda\envs\models\lib\multiprocessing\pool.py", line 239, in _repopulate_pool
    w.start()
  File "C:\Users\Tania\.conda\envs\models\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\Tania\.conda\envs\models\lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "C:\Users\Tania\.conda\envs\models\lib\multiprocessing\popen_spawn_win32.py", line 34, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\Tania\.conda\envs\models\lib\multiprocessing\spawn.py", line 173, in get_preparation_data
    main_mod_name = getattr(main_module.__spec__, "name", None)
AttributeError: module '__main__' has no attribute '__spec__'`

I'm using python 3.5.6, cobra version 0.15.3 and pycharm 2019.1.2.

**Comment by Midnighter** [comment]
FVA by default will recognize and utilize multiple processors in your system. This does not work in an **interactive** environment on Windows. You have two options:

1. You write a Python script that you call non-interactively, e.g., call it from the command line.
2. You disable multiprocessing by decreasing the number of processors configured to 1. You can do this either directly by passing `processes=1` to the FVA function or you can do so in general:
   ```python
   import cobra

   config = cobra.Configuration()
   config.processes = 1
   ```

Please feel free to re-open this issue if your problem isn't solved.
